### ISSUE TITLE
"ffmpeg2" is missing in 2018Q1

### ISSUE THREAD

**Issue by jcea** [TritonDataCenter/pkgsrc#101]
In release 2017Q4, package ```ffmpeg2``` was available. It is not available in 2018Q1.

2017Q4:
```
[root@Transcoding ~]# pkgin search ffmpeg2
ffmpeg2theora-0.30nb2  Simple converter to create Ogg Theora files
ffmpeg2-2.8.13 =     Decoding, encoding and streaming software (v2.x)
```

2018Q1:
```
[root@Transcoding ~]# pkgin search ffmpeg2
No results found for ffmpeg2
[root@Transcoding ~]# pkgin search ffmpeg
No results found for ffmpeg
[root@Transcoding ~]# pkgin search ffmpeg3
No results found for ffmpeg3
```

I will stick this zone in 2017Q4 since it is a LTS and I need "ffmpeg2"...

**Comment by mamash** [comment]
Yes, a recent update to x264-devel re-enabled assembler code, which is breaking the build on SunOS. I'll deal with it.

**Comment by jcea** [comment]
Thanks, @mamash . Please, let me know when available. I use this zone for audio/video transcoding/streaming and I would like to be able to use 2018Q1.

Thanks a lot for your time and effort. Much appreciated.

**Comment by mamash** [comment]
Available now.

**Comment by jcea** [comment]
Oh, Thanks, @mamash . Now I have an issue with pulseaudio. I have a dependency of "pulseaudio >=9.0", but pulseaudio is not available in 2018Q1. Is it dropped for good or a package creation failure?.

Thanks!.

**Comment by jcea** [comment]
Verified. Thanks!
