### ISSUE TITLE
MATE and other meta-packages not found?

### ISSUE THREAD

**Issue by priyadarshan** [TritonDataCenter/pkgsrc#103]
On a freshly installed OmniOS r151026 (AMD Ryzen Threadripper 1950X / X399) I was able to install Awesome WM via Joyent pkgsrc: https://imgur.com/a/sTr41E0

But it seems meta-packages are not installable?

I see they are available in the repo, but, for example, I tried to install MATE, like in [this image on Joyent's site](https://pkgsrc.joyent.com/img/illumos-desktop-mate.png) but it cannot be found

```
root@omniosce:~# pkgin install mate
calculating dependencies... done.
nothing to do.
```

Is there a special command to give in order to install meta-packages? I could not find any related documentation on [pkgsrc](https://www.netbsd.org/docs/pkgsrc/) site.

**Comment by jperkin** [comment]
Unfortunately some packages are missing in the most recent release due to issues with spidermonkey, these have since been resolved but haven't been backported to the release branch - I'll see about doing this.  In the meantime you could use the previous 2017Q4 release where these meta packages are available.

**Comment by priyadarshan** [comment]
Thank you for the explanation. I can definitely wait, and I can test the backports if you wish.

>  In the meantime you could use the previous 2017Q4 release where these meta packages are available.

I take it you mean manually copying over the desired metaport subdirectory from 2017Q4 to my local 2018Q1 tree?

**Comment by jperkin** [comment]
Sorry for not being clear, no I meant using the 2017Q4 bootstrap kit, but that can be a hassle if you're already using 2018Q1 for other things.  I've pushed this fix now, and it should be available within a few hours so it's probably just simplest to wait.  I'll let you know when it's ready.

**Comment by priyadarshan** [comment]
Thanks, I understand now. Thank you for the fix.

**Comment by jperkin** [comment]
Apologies, looks like I was mistaken - the version of spidermonkey I fixed is not the one that a bunch of desktop packages depend on (via polkit).  I'm going to have to port the patches to a newer version.

That may take a little while, so it may be that we just have to wait for 2018Q2 for these packages to be available again.  I'll keep this ticket updated with progress in the meantime.

**Comment by priyadarshan** [comment]
Thanks for the heads up. Let me know if I can be of any help testing. I am sorry I can't be more useful at the moment. I am new to illumos/pkgsrc, ultimately I would like to contribute in more substantial ways.

**Comment by priyadarshan** [comment]
It seems Firefox is also not available. It is listed in the [recent changes](https://github.com/joyent/pkgsrc/wiki/about:changes#changes-in-pkgsrc-2018q1), but I get 
```
priyadarshan@omniosce:~# sudo pkgin install firefox
calculating dependencies... done.
nothing to do
```
Probably affected by same issues as spidermonkey.

**Comment by priyadarshan** [comment]
I have verified `mate` and `firefox` get intalled smoothly. I also tested `vlc2`.

This issue could be closed, as far as I'm concerned.

Thank you very much for the hard work. Joyent's pkgsrc is a real boon.

**Comment by jperkin** [comment]
Great, thank you!
