### ISSUE TITLE
p5-Text-BibTeX: build path was leaked into dylib reference

### ISSUE THREAD

**Issue by anadrome** [TritonDataCenter/pkgsrc#104]
When doing a `full-upgrade`, I get this warning:

    /Users/pbulk/build/textproc/p5-Text-BibTeX/work/Text-BibTeX-0.85/btparse/src/libbtparse.dylib, needed by p5-Text-BibTeX-0.85 is not present in this system.
    proceed ? [y/N]

My installed version is 0.80nb1; current in the repository is 0.85. This is on macOS Sierra, using the repository `https://pkgsrc.joyent.com/packages/Darwin/trunk/x86_64/All`.

**Comment by jperkin** [comment]
Thanks, that shouldn't happen, I'll fix this and also figure out why the checks for correct library paths is failing in this case.

**Comment by jperkin** [comment]
This was fixed in https://github.com/NetBSD/pkgsrc/commit/7fb398b102d322254494beb6c739572833d52fd6
