### ISSUE TITLE
"pulseaudio" missing in 2018Q1

### ISSUE THREAD

**Issue by jcea** [TritonDataCenter/pkgsrc#106]
In release 2017Q4, package ```pulseaudio``` was available. It is not available in 2018Q1:

2017Q4:

```
[root@Transcoding ~]# pkgin search pulseaudio
...
pulseaudio-11.1nb1 = Sound server for POSIX and Win32 systems
...
```

2018Q1:

```
[root@Transcoding ~]# pkgin search pulseaudio
No results found for pulseaudio
```

I use this zone for audio/video transcoding/streaming and I would like to be able to use 2018Q1.

Some context in #101, but I have decided to open a separate issue.

**Comment by mamash** [comment]
The problem lies in polkit that was broken by spidermonkey. The fix would involve importing a whole new version of spidermonkey and a major update of polkit, and sounds like an overkill to me - on a non-LTS release like 2018Q1 (2018Q2 will have the commits already).

Is there a reason why you're keen on using 2018Q1 and not a maintained release like 2017Q4?

**Comment by jcea** [comment]
@mamash, I rather prefer to use up to date packages. I am usually interested in new features in Python, Apache, Bind, dovecot, etc. I don't care a lot about LTS, I redeploy entire instances with Ansible, so upgrading zones quarterly is just regular business.

Currently I use 2018Q1 in all my zones except in the transcoding zones (running 2017Q4 because this and similar issues). Having different OS versions in different zones is... annoying and confusing.

I can run 2017Q4 in those zones for now if you say than 2018Q2 will include multimedia decoding/encoding packages like 2017Q4 does. I can manage to compile mplayer/mencoder myself, but I need the infrastructure to be there: pulseaudio, ffmpeg, mkv tools, etc.

Availability in 2018Q2 is good enough for me. Can I count on it?

Thanks a lot for your time and effort, @mamash.

**Comment by jperkin** [comment]
Yes, these will be fixed in 2018Q2.

**Comment by jperkin** [comment]
This was fixed in 2018Q2.

**Comment by jcea** [comment]
Verified. Thanks!
