### ISSUE TITLE
[darwin] Missing package: lilypond

### ISSUE THREAD

**Issue by baskerville** [TritonDataCenter/pkgsrc#109]
[lilypond](http://lilypond.org/) seems to be missing.

**Comment by mamash** [comment]
This seems to be cause by a known bug in guile that cannot dynamically open a shared lib on Darwin platforms. The build error can be worked around by disabling documentation from being built/installed, but I can't guarantee the problem won't affect Lilypond usage in other ways.

https://stackoverflow.com/questions/3805991/lilypond-mac-os-x-build-issue

https://www.mail-archive.com/bug-guile@gnu.org/msg05781.html

**Comment by mamash** [comment]
I'm on a way to a proper fix for guile, hang on.

**Comment by mamash** [comment]
I committed a fix to libguile and lilypond and the package should build on Darwin next time we refresh the macosx/trunk branch.
