### ISSUE TITLE
 installation on MacOS High Sierra

### ISSUE THREAD

**Issue by knightjp** [TritonDataCenter/pkgsrc#111]
`curl -sS https://pkgsrc.joyent.com/pgp/1F32A9AD.asc | gpg --import`
Following the installation commands on the site and I hit a roadblock.. 
I get an error saying... 
`-bash: gpg: command not found
(23) Failed writing body`

Any ideas?

**Comment by jperkin** [comment]
That section is optional, as gnupg is not shipped on macOS by default, but the instructions are provided anyway for security-conscious users who already have gpg available.

Let me know if I need to improve the instructions to make that clearer.  Thanks.
