### ISSUE TITLE
[darwin] tesseract: tessdata version mismatch

### ISSUE THREAD

**Issue by baskerville** [TritonDataCenter/pkgsrc#113]
*tesseract* spams the standard error with lines starting with `ParamsModel::Incomplete line` when `-l fra` is used. The explanation is [quite simple](https://github.com/tesseract-ocr/tesseract/issues/373#issuecomment-263587877): the training data (at least in the case of `/opt/pkg/share/tessdata/fra.*`) doesn't match the version of *tesseract*. The proper files are available [here](https://github.com/tesseract-ocr/tessdata/tree/3.04.00).

**Comment by mamash** [comment]
Yep, the package was updated at some point to use the version 4 data. No idea why. I'll fix that.

http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/graphics/tesseract/Makefile.diff?r1=1.31&r2=1.32

**Comment by mamash** [comment]
I committed the change to upstream CVS, the Darwin package will get a new reversion number with the next rebuild.
