### ISSUE TITLE
"Mac OS X" should be "macOS"

### ISSUE THREAD

**Issue by jlmuir** [TritonDataCenter/pkgsrc#114]
References to "Mac OS X" or "OSX" should be changed to "macOS" in the wiki (e.g., Package Development [Setup](https://github.com/joyent/pkgsrc/wiki/pkgdev:setup) and [Bulk Builds](https://github.com/joyent/pkgsrc/wiki/pkgdev:bulk)).  If I could fork the wiki and submit a PR I would, but GitHub doesn't seem to allow that!

**Comment by jperkin** [comment]
Fixed in https://github.com/joyent/pkgsrc/wiki/pkgdev:bulk/bd888925f0b3641bc226e87aeebdc7692d1af4cb, thanks.

Yeh, GitHub's wiki handling is a bit weird, I'd have thought they'd just have an interface similar to a regular repository, but it's a bit clunky unfortunately.

**Comment by jperkin** [comment]
I created a separate repository at https://github.com/joyent/pkgsrc-wiki which can be used for issues and pull requests.
