### ISSUE TITLE
Emacs and core dumps

### ISSUE THREAD

**Issue by mikeowens** [TritonDataCenter/pkgsrc#115]
I know there is a long history with this, and maybe it will never be resolved, but is it still the assumed that Emacs is going core dump constantly due to it's linking to libumem? I can't go more than 10 or 15 minutes without a coredump. I just need to confirm that this is just a fact of life so I can either try to live with it or make any possible adjustments.

**Comment by jperkin** [comment]
Yes but it shouldn't be, is it? Maybe we missed one of the versions..

**Comment by mikeowens** [comment]
I compiled emacs25-25.3nb8 from commit 28aa778f3514caaf5f6754c70e6da8574a2f2895 for reference. I am using X11 over SSH, in case that introduces any other known issues. I will rebuild everything from scratch in a new zone and test just to make sure I haven't done something wrong/weird.

**Comment by jperkin** [comment]
Ah ok, if you compiled yourself outside of a pkgbuild image (https://github.com/joyent/pkgsrc/wiki/pkgdev:setup) then it will likely be linked against libumem.  The logic that excludes emacs is here: https://github.com/joyent/pkgbuild/blob/master/include/libumem.mk

**Comment by mikeowens** [comment]
Thank you. I compiled myself bc I am on OmniOS CE. I will try doing pkgbuild image.

**Comment by mikeowens** [comment]
I can't figure out how to get pkgbuild to work on OmniOS CE. It's not officially supported. Is there some simple way I can just patch the build itself within pkgsrc? Maybe I'll just move to SmartOS.

**Comment by jperkin** [comment]
Hm, if you're compiling yourself it may just be leaking from a dependency, you can use `ldd -s` to see where the libumem dependency is coming from.  If it's still coming directly from emacs somehow, you could add `BUILDLINK_TRANSFORM+= rm:-lumem` to the pkgsrc emacs Makefile which will strip any `-lumem` flags from the compiler.

**Comment by mikeowens** [comment]
Ok thank you. There's a ton of of deps that bring libumem in. I removed them and I am going to try and build with that Makefile option and see what happens.

**Comment by mikeowens** [comment]
Well I pretty much rebuilt the entire userland without libumem and manages to get emacs to build without it. Now when I run it, I get: 

```emacs: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs```

And it dies. I've done all I can do.

**Comment by jperkin** [comment]
@richlowe any ideas?

**Comment by richlowe** [comment]
@jperkin None, I'm not familiar with it failing even without libumem

**Comment by mikeowens** [comment]
I'm just going to use SmartOS. I assume it works correctly there.

**Comment by mikeowens** [comment]
An update regarding this issue: Emacs 27 and later no longer has this problem. The cause seemed to be the aging "dumper" in Emacs. It does some shifty things with memory which libumem would not tolerate. In version 27 they replaced the old dumper with a complete rewrite. So far from my testing I have not seen any crashes. Details on the new portable dumper are here: https://dancol.org/pdumperpres.pdf.

Emacs 27 can be built from the the `wip/emacs-git` package.
