### ISSUE TITLE
unresolvable dependencies for gvfs

### ISSUE THREAD

**Issue by mrferda** [TritonDataCenter/pkgsrc#125]
gvfs tries to pull in talloc and samba3, these two conflict (talloc depends on samba4).
Tested on trunk.

**Comment by jperkin** [comment]
Looks like this is a bug in pkgin where one of the database queries is not strict enough, it's simply matching on "samba" and getting results for samba-4.x when the dependency is on samba-3.x.  I'll try and get this in for 2018Q2 (will need some testing to ensure it doesn't cause regressions).

**Comment by jperkin** [comment]
Fixed in https://github.com/joyent/pkgin/commit/f64932c8f7a46745094c92faff7a95539f5d00bf and pkgin 0.11.4, will be in trunk and the 2018Q2 release shortly.
