### ISSUE TITLE
[request] virtualbox

### ISSUE THREAD

**Issue by priyadarshan** [TritonDataCenter/pkgsrc#133]
Virtualbox ia [available as Solaris binary file](https://www.virtualbox.org/wiki/Downloads), but it does not install on OmniOS becasue of missing dependencies. [OpenIndiana has a wiki page about it](https://wiki.openindiana.org/oi/7.2+VirtualBox).

Virtualbox seems to be available in the pkgsrc's [WIP branch](http://pkgsrc.se/wip/virtualbox).

Would it be possible to add Virtualbox to Joyent's pkgsrc at some point?

**Comment by jperkin** [comment]
To be honest it's unlikely to be something that we would work on, but it would be great to see the community provide some patches, it should certainly be possible to build.

**Comment by priyadarshan** [comment]
I know, already being able to boot ISO via `bhyve` kinds of limits usefulness of Virtualbox. But Virtualbox covers a different use case that, say, Windows on bhyve.

Let's hope somebody in `pkgsrc` community will give a hand. It would be quite nice to have.

Thank you!

**Comment by despair86** [comment]
on oi-hipster, the vbox in IPS is now _almost_ up-to-date: v6.0.4

**Comment by priyadarshan** [comment]
If it may help, [OmniOS added Virtual Box](https://github.com/omniosorg/omnios-extra/tree/master/build/virtualbox) towards the end of last year, still on 5.2.28 though.
