### ISSUE TITLE
tcl-expect binary package missing?

### ISSUE THREAD

**Issue by hakansonOHSU** [TritonDataCenter/pkgsrc#136]
I'm using Joyent pkgsrc, x86_64, on macOS High Sierra.  There appears to be no sign of the "expect" binary, which I think should be in the lang/tcl-expect package.  "pkgin search expect" turns up Perl and python expect modules, but not the "real" one.

**Comment by jperkin** [comment]
This is fixed and will be in the next build in a few days time.

**Comment by hakansonOHSU** [comment]
Thanks!

Regards,

Marion
