### ISSUE TITLE
RCS binaries failing on Mac

### ISSUE THREAD

**Issue by hakansonOHSU** [TritonDataCenter/pkgsrc#137]
Joyent pkgsrc binaries running on macOS High Sierra, x86_64.

The RCS binaries in the "rcs-5.9.4" package are crashing on this system.  Any attempt to run a command seems to immediately halt, printing the error message "Abort", with the command's exit status being 262, which indicates signal 6, or SIGABRT.

`
$ /opt/pkg/bin/rcs log .cshrc
Abort
ORPB286 1722$ echo $?
262
$ sudo dtruss -a /opt/pkg/bin/rcs log .cshrc
dtrace: system integrity protection is on, some features will not be available

	PID/THRD  RELATIVE  ELAPSD    CPU SYSCALL(args) 		 = return
 8182/0x1a783:      2170      99     39 open("/dev/dtracehelper\0", 0x2, 0xFFFFFFFFE001FA60)		 = 3 0
 8182/0x1a783:      2724     556    551 ioctl(0x3, 0x80086804, 0x7FFEE001F9C0)	 = 0 0
 8182/0x1a783:      2733      11      6 close(0x3)		 = 0 0
 8182/0x1a783:      2794       8      4 access("/AppleInternal/XBS/.isChrooted\0", 0x0, 0x0)		 = -1 Err#2
 8182/0x1a783:      2839       6      0 thread_selfid(0x0, 0x0, 0x0)		 = 108419 0
 8182/0x1a783:      2845       9      3 bsdthread_register(0x7FFF67C46BEC, 0x7FFF67C46BDC, 0x2000)		 = 1073742047 0
 8182/0x1a783:      2944       5      0 issetugid(0x0, 0x0, 0x0)		 = 0 0
 8182/0x1a783:      3062       8      3 mprotect(0x10FC26000, 0x1000, 0x0)	 = 0 0
 8182/0x1a783:      3065       4      1 mprotect(0x10FC2B000, 0x1000, 0x0)	 = 0 0
 8182/0x1a783:      3079       4      1 mprotect(0x10FC2C000, 0x1000, 0x0)	 = 0 0
 8182/0x1a783:      3081       4      1 mprotect(0x10FC31000, 0x1000, 0x0)	 = 0 0
 8182/0x1a783:      3096       5      2 mprotect(0x10FC24000, 0x88, 0x1)	 = 0 0
 8182/0x1a783:      3105       5      1 mprotect(0x10FC32000, 0x1000, 0x1)	 = 0 0
 8182/0x1a783:      3110       7      3 mprotect(0x10FC24000, 0x88, 0x3)	 = 0 0
 8182/0x1a783:      3130       5      2 mprotect(0x10FC24000, 0x88, 0x1)	 = 0 0
 8182/0x1a783:      3493       5      0 getpid(0x0, 0x0, 0x0)		 = 8182 0
 8182/0x1a783:      3501       7      3 stat64("/AppleInternal/XBS/.isChrooted\0", 0x7FFEE001F098, 0x0)		 = -1 Err#2
 8182/0x1a783:      3505       4      1 stat64("/AppleInternal\0", 0x7FFEE001F130, 0x0)		 = -1 Err#2
 8182/0x1a783:      3540       5      1 csops(0x1FF6, 0x7, 0x7FFEE001EBD0)	 = -1 Err#22
dtrace: error on enabled probe ID 2198 (ID 557: syscall::sysctl:return): invalid kernel access in action #11 at DIF offset 28
 8182/0x1a783:      3606       4      1 csops(0x1FF6, 0x7, 0x7FFEE001E4C0)	 = -1 Err#22
 8182/0x1a783:      3844      54      0 sigaltstack(0x7FFEE00207F8, 0x0, 0x0)	 = 0 0
 8182/0x1a783:      3900       5      0 sigaltstack(0x7FFEE00205A8, 0x0, 0x0)	 = 0 0
 8182/0x1a783:      3973     438     29 open("RCS/.cshrc,v\0", 0x0, 0x0)	 = 3 0
 8182/0x1a783:      3996       8      3 fstat64(0x3, 0x7F90D60030F0, 0x0)	 = 0 0
 8182/0x1a783:      4006       5      0 sigaction(0xA, 0x0, 0x7FFEE0020260)	 = 0 0
 8182/0x1a783:      4008       3      0 sigaction(0xA, 0x7FFEE0020228, 0x0)	 = 0 0
 8182/0x1a783:      4028      15      7 mmap(0x0, 0x6538, 0x1, 0x1, 0x3, 0x0)	 = 0x10FEB6000 0
 8182/0x1a783:      4044       5      0 madvise(0x10FEB6000, 0x6538, 0x2)	 = 0 0
 8182/0x1a783:      4163      10      5 proc_info(0x2, 0x1FF6, 0x11)		 = 56 0
 8182/0x1a783:      4282      11      3 proc_info(0x2, 0x1FF6, 0x11)		 = 56 0
dtrace: error on enabled probe ID 2198 (ID 557: syscall::sysctl:return): invalid kernel access in action #11 at DIF offset 28
 8182/0x1a783:      4353       6      1 issetugid(0x0, 0x0, 0x0)		 = 0 0
 8182/0x1a783:      4500      14      7 shm_open(0x7FFF67C3BDEF, 0x0, 0x0)	 = 4 0
 8182/0x1a783:      4507      11      6 mmap(0x0, 0x1000, 0x1, 0x1, 0x4, 0x0)	 = 0x10FEFD000 0
 8182/0x1a783:      4511       7      2 close_nocancel(0x4)		 = 0 0
 8182/0x1a783:      4531       5      1 ulock_wake(0x102, 0x10FEBD400, 0x0)	 = -1 Err#2
 8182/0x1a783:      4536       4      0 ulock_wake(0x102, 0x10FEBD280, 0x0)	 = -1 Err#2
 8182/0x1a783:      4542       4      0 ulock_wake(0x102, 0x10FEBD300, 0x0)	 = -1 Err#2
 8182/0x1a783:      4558       5      0 sigprocmask(0x2, 0x7FFEE001E934, 0x0)	 = 0x0 0
 8182/0x1a783:      4566      11      6 abort_with_payload(0x12, 0x2, 0x7FFEE001E9C0)		 = 0 0

CALL                                        COUNT
abort_with_payload                              1
access                                          1
bsdthread_register                              1
close                                           1
close_nocancel                                  1
fstat64                                         1
getpid                                          1
ioctl                                           1
madvise                                         1
shm_open                                        1
sigprocmask                                     1
thread_selfid                                   1
csops                                           2
issetugid                                       2
mmap                                            2
open                                            2
proc_info                                       2
sigaction                                       2
sigaltstack                                     2
stat64                                          2
sysctl                                          2
ulock_wake                                      3
mprotect                                        8

$
`

**Comment by jperkin** [comment]
I pushed a fix for this, look out for the rcs-5.9.4nb1 package update in a few days time.

**Comment by hakansonOHSU** [comment]
Glad to hear it.

Thanks and regards,

Marion
