### ISSUE TITLE
postgresql10-server-10.4 does not initialize the database cluster on install

### ISSUE THREAD

**Issue by brianewell** [TritonDataCenter/pkgsrc#138]
Whereas the postgresql96-server-9.6.9 package does successfully initialize the database cluster on install.  I'm assuming this is a regression, and not some new feature of PostgreSQL 10?

Instance: (base-64 18.2.0)
Pkgsrc: 2018Q2

**Comment by jperkin** [comment]
We hadn't copied the INSTALL script in our build repository for the new version, this was fixed a while ago and will appear in 2018Q3.
