### ISSUE TITLE
[darvin] bootstrap-trunk-x86_64-20171103.tar.gz is not installing manpaths.d path config

### ISSUE THREAD

**Issue by kaznovac** [TritonDataCenter/pkgsrc#142]
bootstrap installs paths.d config (10-pkgsrc) but there is no configuration for manpaths

this is super easy to fix by creating `\private\manpaths.d\10-pkgsrc` file with single line `/opt/pkg/share/man`
(just be aware that (The MANPATH environment variable will not be modified unless it is already set in the environment.) [from path_helper man file] )

p.s.
sorry if this is wrong repository i couldn't find bootstrap repository/tracker

**Comment by jperkin** [comment]
Fixed, thanks! I will generate a new bootstrap kit with this fix in the next day or so when the current build has finished.  The correct repository would have been joyent/pkgbuild but don't worry about it too much, we can pick them up from either.
