### ISSUE TITLE
Build x264-devel with asm enabled?

### ISSUE THREAD

**Issue by mrferda** [TritonDataCenter/pkgsrc#147]
Currently x264-devel is built with
--disable-asm
I built a version with asm enabled and got a 4x speed increase (admittedly a different x264 version and newer gcc). The output file didn’t have any visible artifacts.
If I understand the following link correctly OpenIndiana also builds x264 with asm enabled.
https://github.com/OpenIndiana/oi-userland/blob/oi/hipster/components/encumbered/x264/Makefile

**Comment by jperkin** [comment]
They use an older version which we also previously enabled asm for.  I'll see if I can get some time to fix the assembly in the newer release that we use.
