### ISSUE TITLE
RTP: lastpass-cli

### ISSUE THREAD

**Issue by bahamat** [TritonDataCenter/pkgsrc#15]
Request to package lastpass-cli.

https://github.com/lastpass/lastpass-cli

I am currently using Homebrew for this on macOS.

**Comment by jperkin** [comment]
Imported in https://github.com/NetBSD/pkgsrc/commit/62022f1123689848cf53202267985c7d9f5a560c, will be available in the next macOS build.

**Comment by jperkin** [comment]
This is now available in the x86_64 repository.
