### ISSUE TITLE
beats package is missing in 2018Q3

### ISSUE THREAD

**Issue by jfqd** [TritonDataCenter/pkgsrc#151]
Might it be possible to get the beats package back in 2018Q3?

**Comment by jperkin** [comment]
This is available in the trunk package set which I'd recommend upgrading to.  If you specifically require it in 2018Q3 I can look to backport the fix.

**Comment by jfqd** [comment]
Thx a lot Jonathan! Will switch to trunk package soon. So no backport needed :)

**Comment by jfqd** [comment]
@jperkin issue #156 hold me back switching to trunk :(
