### ISSUE TITLE
php 7.2 errors in 2018Q3

### ISSUE THREAD

**Issue by jfqd** [TritonDataCenter/pkgsrc#152]
After updating our [matomo mibe build](https://github.com/jfqd/mi-qutic-piwik) to latest pkgsrc 2018Q3 with php 7.2 I got the following error (extracted from lots of errors for all the other php modules):

```
PHP Warning:  PHP Startup: bcmath: Unable to initialize module\nModule compiled with build ID=API20170718,NTS\nPHP    compiled with build ID=API20170718,TS\nThese options need to match\n in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'zlib.so' (tried: /opt/local/lib/php/20170718/zlib.so (ld.so.1: httpd: fatal: relocation error: file /opt/local/lib/php/20170718/zlib.so: symbol core_globals: referenced symbol not found), /opt/local/lib/php/20170718/zlib.so.so (ld.so.1: httpd: fatal: /opt/local/lib/php/20170718/zlib.so.so: open failed: No such file or directory)) in Unknown on line 0
```

Do these packages need to be recompile?

**Comment by jfqd** [comment]
Think not only for us this issue is critical, because PHP 7.0 is out of support and 7.1 only gets security updates.

**Comment by jfqd** [comment]
Here is the related document of [supported php versions](https://secure.php.net/supported-versions.php).

**Comment by jfqd** [comment]
Any updates on this? Yesterday I tested php 7.3 on trunk: same error as with php 7.2 on 2018Q3!
So only php 7.1 can be used with SmartOS! php 7.2 and php 7.3 are broken.

**Comment by jperkin** [comment]
This is now fixed and will be in tonight's trunk build.

**Comment by jfqd** [comment]
Can confirm that it is working now :)
