### ISSUE TITLE
help make editors/texstudio compile with a static_cast<float>

### ISSUE THREAD

**Issue by hoewweken** [TritonDataCenter/pkgsrc#154]
Texstudio shows an error while compiling:

The patch is easy, add a static_cast<float> in src/pdfviewer/PDFDocument.cpp

grep log10 pdfviewer/PDFDocument.cpp 
                int maxDigits = 1 + qFloor(log10(static_cast<float>(pdfWidget->realNumPages())));

Please integrate this..

**Comment by hoewweken** [comment]
after patching this the link fails with
ld: fatal: -p option is incompatible with building a static object (-dn, -r, --relocatable)

there is no "-p" option in the respective commandline, so i don't know how to search for a possible fix of this..

**Comment by jperkin** [comment]
I've fixed this in trunk, thanks for the report!

**Comment by hoewweken** [comment]
I'm sorry, but its not done yet..

With hunspell enabled (i think it is by default) we hace two replace NULL with FLAG_NULL tow times in hunspell/affentry.hxx

grep NULL work/texstudio2.12.6/hunspell/affentry.hxx 
                            const FLAG needflag = FLAG_NULL);
  struct hentry *      check_twosfx(const char * word, int len, char in_compound, const FLAG needflag = FLAG_NULL);
                            const FLAG needflag = FLAG_NULL);
                  char in_compound, const FLAG needflag = FLAG_NULL);
//                    const FLAG cclass = FLAG_NULL, const FLAG needflag = FLAG_NULL, char in_compound=IN_CPD_NOT);
                    const FLAG cclass = FLAG_NULL, const FLAG needflag = FLAG_NULL, const FLAG badflag = 0);
  struct hentry *   check_twosfx(const char * word, int len, int optflags, PfxEntry* ppfx, const FLAG needflag = FLAG_NULL);
                 PfxEntry* ppfx, const FLAG needflag = FLAG_NULL);


With this additional patch, the compile seems to be ready, but does not link

ld: fatal: -p option is incompatible with building a static object (-dn, -r, --relocatable)
ld: fatal: flags processing errors
collect2: error: ld returned 1 exit status
*** [texstudio] Error code 1

bmake: stopped in /tank/pkgsrc/trunk/pkgsrc/editors/texstudio/work/texstudio2.12.6
1 error

**Comment by jperkin** [comment]
Make sure you rebuilt x11/qt5-qtbase, I made a change there to fix the -p issue.  As for the hunspell problem, I don't see that (and the package doesn't use PKG_OPTIONS), so will need further details on how to trigger it.
