### ISSUE TITLE
Passenger v5.3.3 in SmartOS 2018Q3 is not working

### ISSUE THREAD

**Issue by jfqd** [TritonDataCenter/pkgsrc#156]
I tried passenger-5.3.3 with ruby24 and ruby25 in a SmartOS 2018Q3 minimal 64bit image. Both packages are failing to server ruby webapps with the following error in the Apache error.log, sadly no core dumps were produced.

```
[Thu Nov 01 16:51:06.954101 2018] [core:error] [pid 31792] [client 10.10.10.10:12843] End of script output before headers: 
[ W 2018-11-01 16:51:06.9676 31769/T3 age/Wat/AgentWatcher.cpp:97 ]: Passenger core (pid=31781) crashed with signal SIGSEGV, restarting it...
``` 

May that have anything to do with the latest gcc updates? passenger-5.3.2 in 2018Q2 is working fine.

**Comment by jfqd** [comment]
And is that the reason why passenger is not in trunk?

**Comment by jfqd** [comment]
I did a build for latest passenger version 5.3.5 for ruby25 (ruby25-passenger and ap24-ruby25-passenger). Build went fine, but packages are failing to server ruby webapps with the same error message.

So maybe it is an gcc7 related issue?

**Comment by jfqd** [comment]
@mamash Do you haven idea how to fix it?

**Comment by jfqd** [comment]
passenger is missing in [trunk](https://pkgsrc.joyent.com/packages/SmartOS/trunk/x86_64/All/).

**Comment by jperkin** [comment]
Could you try this again in either trunk or 2018Q4?  I think this was caused by the GCC exceptions issue that I've fixed in those releases.  Thanks.

**Comment by jfqd** [comment]
@jperkin Passenger seems to be working fine in trunk. Deployed a big app without any issues.

But the packages are missing in 2018Q4. Are you able to backport them?

So only issue #170 stops me from migrating to trunk.

**Comment by jfqd** [comment]
Sorry, forgot to say thank you Jonathan!
