### ISSUE TITLE
latest htop 2.2.0 removes dependency for lxproc

### ISSUE THREAD

**Issue by jubalskaggs** [TritonDataCenter/pkgsrc#157]
Hi joyent - is it possible to get the latest version of htop (2.2.0) available in pkgsrc?  The latest version includes native illumos support and avoids the need to have /system/lxproc in place.

As seen here: http://hisham.hm/htop/index.php?page=downloads

(I'm compiling and installing it with default build options and it's working like a charm)

**Comment by jperkin** [comment]
Sure, I will take a look at this, thanks for letting us know!

**Comment by jperkin** [comment]
Updated in https://github.com/NetBSD/pkgsrc/commit/357a37c54bffdd3728a3ddb42f3e521171382b38
