### ISSUE TITLE
[darwin] Error on upgrade of perl-5.28.0nb1

### ISSUE THREAD

**Issue by kimono-koans** [TritonDataCenter/pkgsrc#158]
Contents of /var/db/pkgin/pkg_install-err.log:

---Nov 05 13:35:15: upgrading perl-5.28.0nb1...
pkg_add: Can't open +CONTENTS of depending package p5-Locale-libintl-1.29
pkg_add: 1 package addition failed

**Comment by jperkin** [comment]
Stupid GitHub auto-close.

**Comment by jperkin** [comment]
I pushed changes to pkg_install a few years ago that resolved this issue.
