### ISSUE TITLE
Java / Scale Build Tools

### ISSUE THREAD

**Issue by Smithx10** [TritonDataCenter/pkgsrc#16]
Would be nice if SmartOS had pkgs for 

SBT http://www.scala-sbt.org/ 
Gradle https://gradle.org/ 
DART Pub  https://www.dartlang.org/tools/pub

**Comment by mamash** [comment]
gradle at least has been in pkgsrc at least February (maybe it's not up to date right now)

**Comment by mamash** [comment]
Irrelevant commit triggered an auto-close again.
