### ISSUE TITLE
[darwin] [request] update hugo static site generator

### ISSUE THREAD

**Issue by khoan** [TritonDataCenter/pkgsrc#160]
current version is 0.51 https://github.com/gohugoio/hugo/releases

thanks.

**Comment by jperkin** [comment]
This was updated in pkgsrc a few weeks ago (https://github.com/NetBSD/pkgsrc/commit/7057a400cc9c33c20f52a4742985b47f33d1ed84), however the macOS bulk builds are a little behind at the moment unfortunately.  We have some new hardware coming online soon which should help.
