### ISSUE TITLE
Add gawk to tools repo

### ISSUE THREAD

**Issue by smokris** [TritonDataCenter/pkgsrc#166]
I'd like to be able to use `gawk` on the SmartOS GZ, since it has some features beyond the GZ's built-in Aho/Kernighan/Weinberger `awk`, and the pkgsrc-provided `nawk`.

**Comment by jperkin** [comment]
Done, this will be in the next trunk build, probably tonight.

**Comment by smokris** [comment]
> Done, this will be in the next trunk build, probably tonight.

Great, thanks!

Today I tried to install it, but it isn't finding it:
```bash
# pkgin up
processing remote summary (https://pkgsrc.joyent.com/packages/SmartOS/trunk/tools/All)...
database for https://pkgsrc.joyent.com/packages/SmartOS/trunk/tools/All is up-to-date
# pkgin in gawk
gawk is not available in the repository
calculating dependencies...done.
nothing to do.
```
Is there anything else I need to do to make this work?  (Or has the next trunk build not yet run?  Is there a way to view the status of that?)

**Comment by jperkin** [comment]
Sorry!  It looks like I added it to the wrong package list.  I've fixed this and it will be in tonight's build (hopefully!).

There's currently no way to view the progress of builds, it's a private Jenkins instance that I don't want to open up to the Internet for obvious reasons, but I would like some way of exposing the results at some point.

**Comment by jperkin** [comment]
Try now.

**Comment by smokris** [comment]
I'm able to install it now, and it works fine.  Thanks!
