### ISSUE TITLE
munin version 2 is missing in trunk

### ISSUE THREAD

**Issue by jfqd** [TritonDataCenter/pkgsrc#170]
Munin packages version 2 are missing in trunk. Would it be possible to get munin-node, munin-common and munin-master back in trunk? Thx!

**Comment by jperkin** [comment]
Ah sorry, I assumed that the versions in pkgsrc had now made the versions from wip obsolete, but they appear to be older.  I'll see about updating the ones in pkgsrc to avoid this.

**Comment by jfqd** [comment]
This would be great! I cannot switch to trunk and 2018Q4 if munin2 is missing :(

**Comment by jfqd** [comment]
@jperkin: @wiedi created a ticket for it: https://github.com/joyent/pkgbuild/issues/16

**Comment by jfqd** [comment]
@jperkin will munin2 be back in trunk?

**Comment by jfqd** [comment]
@jperkin will munin2 be back in trunk?

**Comment by jperkin** [comment]
If someone wants to look at this there is a version 2 available in wip initially created by @drscream - https://github.com/joyent/pkgsrc-wip/tree/master/munin-common

This should be upgraded to whatever is the latest version now available and replace sysutils/munin* in main pkgsrc.

**Comment by drscream** [comment]
`wip/munin-common` has been updated to the latest version. Looking into moving it to `sysutils/`

**Comment by jperkin** [comment]
@drscream nice! thanks ;)

**Comment by drscream** [comment]
Munin version 2.x has been promoted from WIP to `sysutils/`: https://mail-index.netbsd.org/pkgsrc-changes/2019/09/09/msg197250.html

**Comment by jfqd** [comment]
@drscream thanks a lot Thomas!
@jperkin will this be now automatically in trunk?

**Comment by jperkin** [comment]
There's already a build running for today, if it finishes in time then I'll pull again later today to include this change. Thanks @drscream!

**Comment by jfqd** [comment]
@drscream @jperkin Thanks a lot for your work!
