### ISSUE TITLE
rust not finding libssl properly

### ISSUE THREAD

**Issue by papertigers** [TritonDataCenter/pkgsrc#171]
Newer versions of `reqwest` now build on illumos thanks to the removal of a dependency attempting to use reuseport. However, when trying to use the library you are met with an immediate crash because ld can't find libssl.so.1.0.0

Example repo that demonstrates the issue:
https://github.com/papertigers/sslfailure-example

**Comment by papertigers** [comment]
Notes about the env:
- https://pkgsrc.joyent.com/packages/SmartOS/trunk/x86_64/All
- rustc 1.31.1 (rust-1.31.1nb1)

Tested with gcc versions:
- gcc (GCC) 4.9.4
- gcc (GCC) 7.4.0 (gcc7-7.4.0)

**Comment by jperkin** [comment]
The bulk build is still running so the fixed packages aren't available yet, but they have been built so I was able to test that this has been fixed:

```console
$ pkg_add rust pkgconf gcc7 pkg_alternatives

$ git clone https://github.com/papertigers/sslfailure-example
$ cd sslfailure-example

$ cargo run
    Updating crates.io index
 Downloading crates ...
  Downloaded reqwest v0.9.8
...
   Compiling reqwest v0.9.8
   Compiling sslfailure-example v0.1.0 (/root/sslfailure-example)
    Finished dev [unoptimized + debuginfo] target(s) in 2m 49s
     Running `target/debug/sslfailure-example`
body = "<!doctype html>\n<html lang=...
```

I'll close the ticket when the packages have been published.

**Comment by jperkin** [comment]
All done.
