### ISSUE TITLE
Please include dnsdist in trunk

### ISSUE THREAD

**Issue by jfqd** [TritonDataCenter/pkgsrc#179]
`dnsdist` package is missing in trunk and 2018Q4. Would it be possible to bring it back? Thx!

**Comment by jfqd** [comment]
@jperkin ist there a special reason why `dnsdist` package is missing in trunk and 2018Q4?

**Comment by jfqd** [comment]
@jperkin is there a reason why `dnsdist` package is still missing in trunk?
Or do we need to switch to a lx zone cause it is missing?

**Comment by jperkin** [comment]
Failure is here: http://us-east.manta.joyent.com/pkgsrc/public/reports/trunk/x86_64/20190730.1224/dnsdist-1.3.2/build.log

If someone can provide a patch it will reappear quicker, otherwise it'll need to wait until I can look at it.

**Comment by jfqd** [comment]
@jperkin I asked on the powerdns mailinglist and they told me this issue was fixed in version 1.3.3. Would it be possible to give this a try?

**Comment by jperkin** [comment]
sure

**Comment by jperkin** [comment]
I updated this to 1.3.3 which builds fine again: http://mail-index.netbsd.org/pkgsrc-changes/2019/08/02/msg195217.html

Unfortunately the git mirror isn't updating today, so this may not make it into tonight's build.

**Comment by jfqd** [comment]
Thanks a lot again! Will try if it is available!

**Comment by jfqd** [comment]
@jperkin Was there another build lately? Cause I cannot see the `dnsdist` package in trunk.

**Comment by jperkin** [comment]
Unfortunately we're reliant on a piece of NetBSD infrastructure that converts the pkgsrc CVS repository to Git and over to GitHub, and the hardware that performs this task is currently unavailable. We're hoping that it will be fixed soon, but until then there won't be any trunk builds. 

Monitoring https://github.com/NetBSD/pkgsrc will show when it's all running again, hopefully before I go away for 2 weeks this weekend...

**Comment by jfqd** [comment]
@jperkin Thanks!
