### ISSUE TITLE
Import mosquitto into upstream

### ISSUE THREAD

**Issue by sjorge** [TritonDataCenter/pkgsrc#180]
As mentioned on #SmartOS, here is the mosquitto package.
@jperkin all mentioned issues are fixed and pkglint is happy. I've also cleaned up one of the patches to make it more platform agnostic.

```
[isotope :: sjorge][/data/pkgsrc/pbd/mosquitto][master ✗]
[!]$ pkglint
ERROR: Makefile:4: Invalid category "pbd".
1 error and 0 warnings found.
```
Is the only error remaining as I namespace all my package in pbd, this should probably live under net once upstreamed.

Source available from https://github.com/sjorge/pkgsrc-blackdot/tree/master/mosquitto

**Comment by sjorge** [comment]
Just for my future self (or if anyone picks it up earlier)

Feedback from IRC:
- [ ] ask on #pkgsrc for non SmartOS folks to test
- [x] fix `#ifdef _SunOS_` as it should not work (but does?) to use `__sun` (no longer needed on 1.6.x)
- [x] patch in `${PKGMANDIR}` into CMakeLists.txt instead of using Makefile to move them. (no longer done in 1.6.x)

**Comment by papertigers** [comment]
@sjorge have you had any time to drive this over the line?  I am currently using a pkg I built from your repo but would love to have this in pkgsrc proper so I don't have to think about it anymore.

**Comment by sjorge** [comment]
I have not, there were a few things still not done with this for it to go upstream unfortunately.

~ sjorge

**Comment by sjorge** [comment]
Some of the mentioned issues are fixed in 1.6.x, I tried bumping to 1.6.9 today but the build is broken again. Blah.

```
Undefined                       first referenced
 symbol                             in file
DL_INSERT_INORDER                   CMakeFiles/mosquitto.dir/session_expiry.c.o
ld: fatal: symbol referencing errors. No output written to mosquitto
collect2: error: ld returned 1 exit status
```

**Comment by sjorge** [comment]
Fun stuff! It's an upstream bug it seems as both the debian and fedora packages have the error!
https://github.com/eclipse/mosquitto/issues/1637

But pkgsrc is nice enough to catch it before finishing! <3 but also *shakes fist @ upstream*

**Comment by sjorge** [comment]
Using the bundled uthash works 🤷‍♂ , I've pushed the changes to my repo.

**Comment by sjorge** [comment]
@jperkin most of the issue are addressed now, can you see if it builds on one of your netbsd machines?

Aside from the catogory being set to pdb (my own prefix to keep things apart)
