### ISSUE TITLE
openldap-server buckles under load due to file descriptor limit

### ISSUE THREAD

**Issue by bahamat** [TritonDataCenter/pkgsrc#181]
http://www.openldap.org/faq/data/cache/1126.html

OpenLDAP has a hard coded limit limit of 4096 file descriptors. Documentation suggests using the following compile time flag:

    env CPPFLAGS="-DOPENLDAP_FD_SETSIZE=8192" ./configure

This should (based on what I'm reading) work at least as far back as 2.2.30. Older versions may need to use the following instead.

    env CPPFLAGS="-DFD_SETSIZE=8192" ./configure

**Comment by bahamat** [comment]
I need this back ported to 2017Q4.

**Comment by jperkin** [comment]
Can I confirm this is with the x86_64 set? The code appears to be written such that it ignores the operating system default (which in our case would be 64k and plenty), but it's hard to tell as it depends on include ordering.

**Comment by jperkin** [comment]
Fixed in https://github.com/NetBSD/pkgsrc/commit/01a9f8bc69186ba7d18ad8a74d6c8fa620fc2b22, will backport to 2017Q4.

**Comment by jperkin** [comment]
openldap-client-2.4.45nb1 is now available for 2017Q4 x86_64.

**Comment by bahamat** [comment]
What about openldap-server?

**Comment by jperkin** [comment]
The client package provides libldap, which the server links against.

**Comment by bahamat** [comment]
OK, great. That should work.

Thanks!
