### ISSUE TITLE
py27-augeas missing from trunk

### ISSUE THREAD

**Issue by russhan** [TritonDataCenter/pkgsrc#185]
py27-augeas-0.5.0.tgz has existed for a couple of years but not in trunk.

**Comment by russhan** [comment]
I forgot to specify my issue is for SmartOS.  I don't know about the other platforms.

**Comment by russhan** [comment]
I had a direct download of certbot that prompted the attempt at downloading augeas.  I just noticed there's a py37-certbot package.  I downloaded and installed that and my certificate is renewed.

So I, personally, don't need this resolved.

**Comment by jperkin** [comment]
Yeh this hasn't built in a while, I think it's only targetting newer python3 releases now.
