### ISSUE TITLE
copy-paste bug in bind smf start method

### ISSUE THREAD

**Issue by isaacdavis** [TritonDataCenter/pkgsrc#189]
In the start method for the `bind` SMF service, [this line](https://github.com/joyent/pkgsrc/blob/ca643f6a31261f62a31e23f2ce383732ff911ceb/net/bind910/files/smf/named.sh#L114) appears to have been copy-pasted from the case statement immediately above it. The `-t` flag should be removed -- the line should instead read:

     checkopts="${checkopts} ${value}"

This error also exists in `bind` versions 9.11 and 9.12.

We're now using `bind` (version 9.10.7) in the triton-prometheus image, which uses https://pkgsrc.joyent.com/packages/SmartOS/2018Q1/multiarch/All, so it would be excellent if this fix could be backported there as well. Thank you!

**Comment by jperkin** [comment]
Thanks, sorry it's taken so long to integrate this.  I can't backport to 2018Q1 as it's long out of support, but I will backport these to 2018Q4.

**Comment by jperkin** [comment]
These have been backported to 2018Q4 along with a bunch of the latest security fixes. I'm now running the backported `bind-9.12.4pl2` on my personal server and it appears to be working fine.

**Comment by isaacdavis** [comment]
Thanks, Jonathan! This is very helpful.
