### ISSUE TITLE
tmate & tmate-slave

### ISSUE THREAD

**Issue by jussisallinen** [TritonDataCenter/pkgsrc#19]
pkgsrc should provide tmate and tmate-slave.
tmate is basically like Teamviewer but for SSH connections.

https://tmate.io/
https://github.com/tmate-io/tmate-slave

**Comment by jussisallinen** [comment]
Something like this might be around the corner when trying to compile:
https://github.com/tmate-io/tmate-slave/issues/20

**Comment by jperkin** [comment]
Does this add anything compared to a shared tmux session?  My only concern is that they're behind upstream by a few releases now and haven't committed anything in over a year.  It's not clear exactly what it provides compared to just using tmux.

**Comment by jussisallinen** [comment]
tmate provides an easy way to share terminal session as Read-Only or Read-Write, ie. for providing remote debugging access to 3rd party during troubleshooting etc.

As an example: http://tmate.ip.fi/

```
$ tmate show-messages
Tue Aug 22 22:34:35 2017 [tmate] Connecting to tmate.ip.fi...
Tue Aug 22 22:34:35 2017 [tmate] Note: clear your terminal before sharing readonly access
Tue Aug 22 22:34:35 2017 [tmate] ssh session read only: ssh ro-Las1sdGRXOJcG1RejJPVkkFbY@tmate.ip.fi
Tue Aug 22 22:34:35 2017 [tmate] ssh session: ssh THdJOAO6pUD9gt7y3FnMKqvsR@tmate.ip.fi
```

The remote party connecting to the session through tmate server doesn't need anything else than SSH client and username+host provided from tmate session - no client or whatsoever to install.

**Comment by jussisallinen** [comment]
The remote party connecting to the session through tmate server doesn't need anything else than SSH client - no client or whatsoever to install.

**Comment by jperkin** [comment]
tmate added in https://github.com/NetBSD/pkgsrc/commit/4942ff0cbf812e2b5d508b01a610c50b1bb53d20

**Comment by jussisallinen** [comment]
@jperkin Able to add tmate-slave eventually so it would be possible to host your own tmate server?

**Comment by jperkin** [comment]
Yeh, I'm not going to get to this before 2017Q4 though unfortunately.

**Comment by jussisallinen** [comment]
No hurry, if it's available during 2018 that's alright :+1:
