### ISSUE TITLE
perl-5.28.1 and p5-Net-SSLeay

### ISSUE THREAD

**Issue by idodeclare** [TritonDataCenter/pkgsrc#190]
Hello,

I am trying to refresh perl-5.28.1, but `pkgin` fails with the following error from `/var/db/pkgin/pkg_install-err.log`:

```
---Apr 13 16:40:44: refreshing perl-5.28.1...
pkg_add: Can't open +CONTENTS of depending package p5-Net-SSLeay-1.85
pkg_add: 1 package addition failed
```

Sorry I haven't been able to find any troubleshooting tip for a `+CONTENTS` error.

I see from `pkgin search` that there is p5-Net-SSLeay-1.85nb1. Does that "nb1" suffix mean a version mismatch when perl 5.28.1 looks for p5-Net-SSLeay-1.85?

Thank you for your attention.

**Comment by jperkin** [comment]
Stupid GitHub auto-close.
