### ISSUE TITLE
new release of the bootstrap for el7 

### ISSUE THREAD

**Issue by cdorbell2** [TritonDataCenter/pkgsrc#191]
Hello
i'm not sure if it's the good place for request this, it is possible to create a new release of the bootstrap for el7 ?

https://pkgsrc.joyent.com/packages/Linux/el7/bootstrap/
the last version is bootstrap-trunk-x86_64-20170127.tar.gz 

this version have some problem for to be used behind a proxy .

Rgds

**Comment by jperkin** [comment]
I updated this a while ago, hopefully it will resolve any issues you saw.
