### ISSUE TITLE
Missing package: percona-server in 2018Q4 and 2019Q1

### ISSUE THREAD

**Issue by sleepnmojo** [TritonDataCenter/pkgsrc#192]
I can't find percona-server in 2018Q4 or 2019Q1.  It exists in 2018Q3.

**Comment by drscream** [comment]
I would like to add that `percona-server` versions has been build in January for 2018Q4, but it looks like they have been removed from https://pkgsrc.joyent.com. Is there any known issue why they have been removed?

@sleepnmojo not sure if that might be helpful for you, but they are still available at our mirror: https://pkgsrc.smartos.skylime.net/packages/SmartOS/2018Q4/x86_64/All/

**Comment by sleepnmojo** [comment]
Thanks.  I didn't see them in the main repo, so I thought there was an issue with them.  Looks like it is the main repo that has the issue.

**Comment by jacques** [comment]
Thanks @drscream.

**Comment by jacques** [comment]
@mamash any chances that this can be built on 2019Q1?

**Comment by jperkin** [comment]
These are now available again in 2018Q4 (mirrors will have them within the next hour or so).

**Comment by jacques** [comment]
Any chances of getting this into 2019Q1?

**Comment by jperkin** [comment]
No, 2019Q2 will be released very shortly and 2019Q1 is no longer supported.
