### ISSUE TITLE
GNU uname should identify OS as illumos

### ISSUE THREAD

**Issue by jclulow** [TritonDataCenter/pkgsrc#195]
As of [bug 1956](https://www.illumos.org/issues/1956), the `uname` binary provided by the operating system will report `illumos` for `uname -o` instead of the traditional `Solaris`.  Unfortunately in a pkgsrc-based zone, at least under some conditions the GNU `uname` appears first in `PATH`.  A naive script may run `uname -o` and see the `Solaris` value.

We should patch the pkgsrc copy of `uname` to report `illumos` as the system version does.

See example with current trunk packages:

```
$ /usr/bin/uname -o
illumos
$ /opt/local/bin/uname -o
Solaris
```

**Comment by wiedi** [comment]
A long time ago I played with this and had the following:

```
diff --git a/sysutils/coreutils/Makefile b/sysutils/coreutils/Makefile
index 82c440e..cdf8ce7 100644
--- a/sysutils/coreutils/Makefile
+++ b/sysutils/coreutils/Makefile
@@ -43,6 +43,11 @@ SUBST_FILES.libname= Makefile.in
 SUBST_SED.libname=     -e '/^src_libstdbuf_so_LDFLAGS/s,$$, -install_name ${PREFIX}/libexec/coreutils/glibstdbuf.so,'
 .endif
 
+.if ${OPSYS} == "SunOS"
+CONFIGURE_ENV+=                gl_cv_host_operating_system=illumos
+.endif
+
+
 PROGS= [ base64 basename cat chcon chgrp chmod chown chroot cksum comm \
        cp csplit cut date dd df dir dircolors dirname du hostid echo env \
        expand expr factor false fmt fold groups head id install join kill \
```

But that is lazy way to fix it as it would be wrong when using pkgsrc on Oracle Solaris.
Propably should just try to shell out to `/usr/bin/uname -o` now?

**Comment by jperkin** [comment]
Older Solaris releases don't support `-o` so we'd need to handle that, but yeh that seems the simplest way to do it.

**Comment by jperkin** [comment]
Note that I will need to override this for our builds anyway as they are performed on a platform prior to [1956](https://www.illumos.org/issues/1956).

**Comment by jperkin** [comment]
Fixed in trunk.
