### ISSUE TITLE
Missing package since 2018Q4: dovecot-pigeonhole

### ISSUE THREAD

**Issue by sjorge** [TritonDataCenter/pkgsrc#196]
As the subject says, we're missing dovecot-pigeonhole after 2018Q4, it was hinted on IRC it might have to do with -fPIC but that turned out not to be enough.

File a ticket to not forget about it.

**Comment by jperkin** [comment]
I've figured out the fix for this, it'll be in the next trunk build and will backport as an update to the dovecot packages to 2018Q4.
