### ISSUE TITLE
[darwin] Missing package: mongodb

### ISSUE THREAD

**Issue by baskerville** [TritonDataCenter/pkgsrc#20]
I got this error while trying to upgrade: `pkgin: mongodb-3.4.4 has no associated repository`.

**Comment by jperkin** [comment]
Failure is [here](http://us-east.manta.joyent.com/pkgsrc/public/reports/Darwin/trunk/x86_64/20170826.0819/mongodb-3.4.4nb1/build.log), I'll take a look at this and add it to the required packages list.

**Comment by jfqd** [comment]
Current version is 3.6. But 3.4 is the latest one supported for Solarish systems, right? So sad. https://engineering.mongodb.com/post/farewell-solaris
