### ISSUE TITLE
node v10.16.0 in trunk not usable

### ISSUE THREAD

**Issue by jfqd** [TritonDataCenter/pkgsrc#203]
Latest node version 10.16.0 in trunk, build date: '01-Jun-2019 01:28', is failing to start:

```
$ node --version
ld.so.1: node: fatal: relocation error: R_AMD64_32: file /opt/local/bin/node: symbol getentropy: value 0xfffffc7fef12ac60 does not fit
```

**Comment by jperkin** [comment]
I couldn't reproduce this, was it reproducible for you?  It has been rebuilt with a newer GCC though so I don't have the exact bits that you may have used.

**Comment by jfqd** [comment]
I am using trunk and just installed latest node, same issue:

```
$ node --version
ld.so.1: node: fatal: relocation error: R_AMD64_32: file /opt/local/bin/node: symbol getentropy: value 0xfffffc7fef12ac60 does not fit
Killed
```

**Comment by jperkin** [comment]
What platform version are you running on?

**Comment by jfqd** [comment]
20190509T005736Z

**Comment by jfqd** [comment]
@jperkin  It seems this have been fixed, right?

**Comment by jperkin** [comment]
Yeh sorry, forgot to close this out.
