### ISSUE TITLE
[illumos] aria2 missing from 2017Q2

### ISSUE THREAD

**Issue by jjlawren** [TritonDataCenter/pkgsrc#21]
Has been available in previous releases.

https://github.com/joyent/pkgsrc/tree/trunk/net/aria2

**Comment by jperkin** [comment]
This is available again in 2017Q3 and the new LTS 2017Q4, sorry it took so long to respond to this issue.

**Comment by jjlawren** [comment]
Thanks for the info!

**Comment by jjlawren** [comment]
I've finally gotten around to upgrading to a new 17.4.0 image, but this build seems to segfault immediately with any normal use. Possibly a bad build?

Opened a case at the aria2 project with more details: https://github.com/aria2/aria2/issues/1138

**Comment by jjlawren** [comment]
After some time I've tested with a fresh `minimal-64 18.2.0` image with the same results of immediate segfaults. Any suggestions @jperkin ?
