### ISSUE TITLE
couchdb pkg svc fails to start

### ISSUE THREAD

**Issue by jbarfield** [TritonDataCenter/pkgsrc#211]
Vanilla smartOS zone latest x86_base64 image.

run ‘pkgin up -fy’
run ‘pkgin in -y couchdb’

Installs packages properly but fails to start with erlang errors pertaining to read only filesystems full such as /usr. Unable to start erlang monitoring processes. erlang kernel error.

will post output of errors upon request.

Also ‘svcadm enable -r couchdb’

Fails to enable couch-epmd dependency by default prior to enabling couchdb this must be done manually and then must have couchdb restarted after.

**Comment by jperkin** [comment]
Unless there is a bug in the package these two things should be unrelated. Nothing in packages should be writing to `/usr`, and in any case `/usr` is a read-only mount from the global zone so can't be written to anyway.

Package data should be limited to `/opt/local` for package files and `/var` for any user-generated data.

If the test package I posted on smartos-discuss is still causing errors here then please could you post some more detailed logs and we can take a look at where they may be coming from.
