### ISSUE TITLE
postgrey < 1.37 mishandles common outbound mail pool hostnames

### ISSUE THREAD

**Issue by drboone** [TritonDataCenter/pkgsrc#214]
There's a fix in postgrey 1.37 which removes an ill-considered special case for hostnames.  The offending code ends up causing supposedly whitelisted domains with numbers in their names to be whitelisted.  This ends up triggering on things like outlook.com.

Would be nice if postgrey 1.37 could make it into pkgsrc.

Bug from the postgrey tracker here:
https://github.com/schweikert/postgrey/issues/32

**Comment by jperkin** [comment]
I backported the fix in 78b68e7f7074ae0c55ee3254b16cbe886933ffea, we can't upgrade to 1.37 until there is a working targrey patch available for it.
