### ISSUE TITLE
[darwin] Multiple incompatible libraries not upgraded when ffmpeg3 installed

### ISSUE THREAD

**Issue by kimono-koans** [TritonDataCenter/pkgsrc#22]
Issue fixed with a "pkgin full-upgrade", however received the following errors from youtube-dl:

ERROR:   Reason: Incompatible library version: ffmpeg3 requires version 22.0.0 or later, but libfreetype.6.dylib provides version 20.0.0

ERROR:   Reason: Incompatible library version: ffmpeg3 requires version 12.0.0 or later, but libfontconfig.1.dylib provides version 11.0.0

[NOTE: There are probably additional packages that need to be upgraded.]

Expected behavior:  Packages required for ffmpeg3 should be upgraded when ffmpeg3 is installed

**Comment by jperkin** [comment]
Just a note to say that this type of issue has been fixed since, with the introduction of refresh support in pkgin.
