### ISSUE TITLE
dehydrated-0.4.0nb1 fails to find Replay-Nonce header if fetch is done via HTTP/2

### ISSUE THREAD

**Issue by drboone** [TritonDataCenter/pkgsrc#226]
If dehydrated does a fetch from an acme server, and the transaction is completed using HTTP/2, the returned headers may not be in the same case (e.g. may be all lower case) as the script is grepping for.

https://github.com/lukas2511/dehydrated/commit/e4e712c03ad70bd5100af1333c2801f4b5baa89a

Output when this happens includes:
```
  + Requesting challenge for x.y.org...
  + ERROR: An error occurred while sending post-request to https://acme-v01.api.letsencrypt.org/acme/new-authz (Status 400)

Details:
{
  "type": "urn:acme:error:badNonce",
  "detail": "JWS has no anti-replay nonce",
  "status": 400
}
```

Could this package be updated?  In addition to this bug fix, it appears to include new features like wildcard support and alpn validation.

**Comment by jperkin** [comment]
This was upgraded a while back and is currently the most recent version.
