### ISSUE TITLE
rebuild py-certbot-0.38.0nb3 for 2019Q3

### ISSUE THREAD

**Issue by drscream** [TritonDataCenter/pkgsrc#231]
Because of the last pull-up it would nice if you can rebuild and publish `security/py-certbot-0.38.0nb3` and the new added dependency `devel/py-distro`.

http://pkgsrc.se/branch=pkgsrc-2019Q3/security/py-certbot

**Comment by jperkin** [comment]
Sorry I missed this, 2019Q3 was EOL a long time ago, hopefully newer releases would have fixed this.
