### ISSUE TITLE
Update setup instructions for OpenIndiana Hipster to use gpg2 instead of gpg

### ISSUE THREAD

**Issue by jdrch** [TritonDataCenter/pkgsrc#237]
Following the _Choose Your Illumos Package Set_ & _Upgrades_ [instructions](https://pkgsrc.joyent.com/install-on-illumos/) on OpenIndiana Hipster can be problematic for new users, as attempting to use `gpg` returns `-bash: gpg: command not found`. 

Please update or add documentation to use `gpg2` instead, as that works.

**Comment by jperkin** [comment]
Fixed in https://github.com/joyent/pkgsrc.joyent.com/commit/ef33e1011d667030d24015d8319a4e6f8ead87d5, thanks!

**Comment by jdrch** [comment]
> Fixed in [joyent/pkgsrc.joyent.com@ef33e10](https://github.com/joyent/pkgsrc.joyent.com/commit/ef33e1011d667030d24015d8319a4e6f8ead87d5), thanks!

Yw!

**Comment by liv3010m** [comment]
Hi guys, there is a similar issue with OmniOS bloody where neither gpg2 nor gpg exists. Could this be?
`root@omniosce:~/pkgsrc#  uname -a`
`SunOS omniosce 5.11 omnios-master-5b83ca0623 i86pc i386 i86pc`
`root@omniosce:~/pkgsrc# curl -sS https://pkgsrc.joyent.com/pgp/DE817B8E.asc | gpg2 --import`
`-bash: gpg2: command not found`
`curl: (23) Failed writing body (5120 != 5306)`

**Comment by jperkin** [comment]
As the instructions say, this requires that gpg is installed on the host.  This will differ depending on the illumos distribution you are using.

**Comment by jdrch** [comment]
@liv3010m Google "OmniOS gpg" to find the correct package for your OS. Then run the installation command with it, then then replace the `gpg2` entry in the instructions with that package name.

**Comment by liv3010m** [comment]
Sorry I was to quick to post this. I'm already installing gpg! ;)

**Comment by jdrch** [comment]
> 
> 
> Sorry I was to quick to post this. I'm already installing gpg! ;)

No worries. Once you do that, everything should work.

**Comment by liv3010m** [comment]
Yup, everything up right now. thanks!

**Comment by jdrch** [comment]
> 
> 
> Yup, everything up right now. thanks!

Yw!

**Comment by ahayes** [comment]
SmartOS uses gpg. It looks like this fix broke the instructions for SmartOS and SmartOS GZ. I'm running SmartOS 20200422.

**Comment by jperkin** [comment]
SmartOS does indeed ship with /usr/bin/gpg, but it is a very broken version, I'm surprised you even managed to make it work.

As these instructions are more likely to apply to users coming from other distributions then, given we need to pick one, I'd rather pick the one more likely to be used.  Anyone who is able to work around SmartOS's /usr/bin/gpg not being able to, for example, recv-keys, is probably able to account for the gpg2 vs gpg difference ;)

**Comment by ahayes** [comment]
I removed the "2" after searching and finding this github issue and it worked. So perhaps it is no longer as bad as you thought?

I don't think you are being terribly objective here. Given that the "SmartOS/Illumos" page claims it has instructions for SmartOS and even a specific set of instructions for the "64-bit tools (SmartOS GZ)", I'm not sure that "they are smart enough to figure out that we misled them" is really a great place to leave this, especially on a Joyent page of all places.

Is there some reason the page needs to shared? If so, can it not have two versions of the relevant lines documented instead of picking one? Can the explicit SmartOS GZ instructions not be correct? Maybe three tabs - one for Other Illumos, one for SmartOS Zones, and one for SmartOS Global Zone tools?

**Comment by jdrch** [comment]
> Is there some reason the page needs to shared?

As with nearly all open source projects, manpower is an issue. Maybe all that's needed is a note or table on which `gpg` to use for which Illumos.

**Comment by jperkin** [comment]
Ok, given that the GZ instructions are specific to that environment and unlikely to be used elsewhere I've switched just those back to `gpg`.

Regarding `--recv-keys`, I'd forgotten that I'd already worked around that in the instructions, so the `curl | gpg` bit will make it work.

Hopefully that's to everyone's satisfaction.

**Comment by ahayes** [comment]
OK. Thanks @jdrch and @jperkin 
I don't mind pitching in. I implemented the multiple tabs in a pull request and just submitted it but it looks like there are multiple joyent pkgsrc repos and somehow I wound up on a different one (pkgsrc.joyent.com). It is joyent/pkgsrc.joyent.com#8
