### ISSUE TITLE
conflict xorgproto fixproto

### ISSUE THREAD

**Issue by hoewweken** [TritonDataCenter/pkgsrc#242]
Hello!

After some time I tried to build some interesting packages from a new clean pkgsrc-joyent git-clone.
I tried editor/texstudio and graphics/darktable

There are obviously some dependencies that try to install xorgproto and fixproto,
generating conflicts in 2 files.

pkg_add -v /home1/home/steven/src/pkgsrc-joyent/pkgsrc/packages/All/xorgproto-2019.2nb3.tgz
pkg_add: Conflicting PLIST with fixesproto-4.0nb1: include/X11/extensions/xfixesproto.h
pkg_add: Conflicting PLIST with fixesproto-4.0nb1: include/X11/extensions/xfixeswire.h
pkg_add: 1 package addition failed

One interesting thing is this dependency of fixesproto-4.0nb1:
"Package depends exactly on: xorgproto-2019.2nb3"

As fixesproto seems to be a package for special cases 
"This package is for use with Xfixes only. Do not update to later versions."
 somewhere in the dependencies this package has to be ruled out..(?)

Greetings,
Stephan

**Comment by hoewweken** [comment]
Ah - i'm using openindiana with mk.conf:

cat /opt/pkg/etc/mk.conf 
# Example /opt/pkg/etc/mk.conf file produced by bootstrap-pkgsrc
# 23 February 2020 at 22:05:38 CET

.ifdef BSD_PKG_MK	# begin pkgsrc settings

ABI=			32
PKGSRC_COMPILER=	gcc
GCCBASE=                /usr/gcc/7
USE_NATIVE_GCC=         YES

PKG_DBDIR=		/opt/pkg/pkgdb
LOCALBASE=		/opt/pkg
VARBASE=		/opt/pkg/var
PKG_TOOLS_BIN=		/opt/pkg/sbin
PKGINFODIR=		info
PKGMANDIR=		man

PREFER_PKGSRC=		no

TOOLS_PLATFORM.install?=	/opt/pkg/bin/bsdinstall
TOOLS_PLATFORM.sh?=		/usr/bin/bash

ALLOW_VULNERABLE_PACKAGES= YES

.endif			# end pkgsrc settings

**Comment by hoewweken** [comment]
seems that the error does not occur with X11_type=modular,
my build gives an error now on qt5, but this is a different issue (a local one i suppose..)

In this issue the build with X11_type=native is not working, i suppose the pkgsrc build system does not see (all) of the needed oi-X11-pkgs...(?)

**Comment by jperkin** [comment]
It's likely that there are not many users of native Xorg on OpenIndiana combined with pkgsrc, so yeh you will probably run into some cases where packages are not yet configured to support it.

The main one is `pkgtools/x11-links`, so it's worth starting there to ensure that all of the Xorg libraries that OI installs are correctly linked and made available to pkgsrc.

Sorry, this is just a configuration that I've never worked on so unfortunately you will run into more issues than using `X11_TYPE=modular`.  It would however be really nice for it to be better supported if you were able to work on it.

**Comment by jperkin** [comment]
Going to close this one out for now.
