### ISSUE TITLE
beats package is missing in trunk

### ISSUE THREAD

**Issue by jfqd** [TritonDataCenter/pkgsrc#249]
Might it be possible to get the beats package back in trunk?

**Comment by jfqd** [comment]
@jperkin 2018Q4 was the last build where the beats package was included. Where can I see why this package build failed? If using the ELK-Stack beats is required :/

**Comment by jperkin** [comment]
Head to <https://mail-index.netbsd.org/pkgsrc-bulk/>, find the most recent "pkgsrc-trunk-x86_64 SmartOS" build, click the report URL link and search for any broken package, that will give you the links to the logs, in this case <https://us-east.manta.joyent.com/pkgsrc/public/reports/trunk/x86_64/20200411.1055/beats-6.6.2nb10/build.log>

There used to be some patch for `dup2()`, I wonder if it was dropped somewhere.  I'll take a look.

**Comment by jperkin** [comment]
I updated and fixed this in https://github.com/NetBSD/pkgsrc/commit/57f1b912cabe7994bac8de4f75a5f82881175c2a, it will be in tonight's build.

**Comment by jfqd** [comment]
@jperkin Thx a lot!
