### ISSUE TITLE
OpenIndiana Hipster GUI: How do I ensure my installed pkgsrc packages are always the latest?

### ISSUE THREAD

**Issue by jdrch** [TritonDataCenter/pkgsrc#253]
I run OpenIndianaHipster GUI and would like to ensure that my pkgsrc packages are always the absolute latest available in the repos. 

What is required to do this (it's not particularly clear to me from the [setup instructions](https://pkgsrc.joyent.com/install-on-illumos/))? Is simply running `# pkgin -y full-upgrade` sufficient, or do I *also* have to upgrade from the previous quarterly release pkgsrc trunk set every time a new pkgsrc trunk set quarterly release becomes available?

**Comment by jperkin** [comment]
Nope, you just need to run `pkgin upgrade` every few days.

Previously with the quarterly releases you would have needed to switch repository every 3 months to upgrade to the latest, but the rolling trunk release tracks the very latest daily pkgsrc changes so there's no need to do that.

We still offer the quarterly releases for anyone who doesn't want the hassle of continually upgrading or needs specific versions to be locked, and that's what we provide to our SmartOS users in the form of zone images, but for anyone else it's recommended to just use the trunk packages that I made the default as it's the most suitable for most people.

Side note, `pkgin upgrade` is now the recommended method for upgrading.  Recent versions of pkgin made `upgrade` and `full-upgrade` equivalent, with the latter becoming deprecated.

**Comment by jdrch** [comment]
Thanks for the info!

> Side note, `pkgin upgrade` is now the recommended method for upgrading. Recent versions of pkgin made `upgrade` and `full-upgrade` equivalent, with the latter becoming deprecated.

That's good to know. Do you know who manages the setup instructions? They should probably be updated accordingly. I submitted a [request](https://github.com/joyent/pkgsrc/issues/237) for `gpg` to be changed to `gpg2` (the instructions will fail on OI Hipster with the former) but nothing's happened since. I don't mind making the edit or maintaining a separate page for OI myself if nobody has the time; just let me know.

**Comment by jperkin** [comment]
That would be me ;)  I'll take a look, sorry for missing that.

**Comment by jperkin** [comment]
I've fixed that issue now, as well as updating the instructions to use `pkgin upgrade` where appropriate.

**Comment by jdrch** [comment]
> 
> 
> I've fixed that issue now, as well as updating the instructions to use `pkgin upgrade` where appropriate.

Many thanks :)
