### ISSUE TITLE
PowerDNS recursor missing

### ISSUE THREAD

**Issue by zylantha** [TritonDataCenter/pkgsrc#254]
PowerDNS appears to have been bumped to 4.2.1, however with the recursor now split into a separate executable, the recursor executable needs to be built into the main package or included in a separate add-on package which isn't available in SmartOS.

Can the PowerDNS package please include a build of the recursor, or available as a separate add-on package?

A version bump to the current release of PowerDNS-4.3 would also be timely.

**Comment by jperkin** [comment]
Yeh the recursor package is currently failing to build:

https://us-east.manta.joyent.com/pkgsrc/public/reports/trunk/x86_64/20200411.1055/powerdns-recursor-4.3.0/build.log

I'll take a look.

**Comment by jperkin** [comment]
I've raised an upstream bug for this: https://github.com/PowerDNS/pdns/issues/9025

**Comment by jperkin** [comment]
This is now available in trunk.
