### ISSUE TITLE
[request] XtraBackup 8.0.11

### ISSUE THREAD

**Issue by jfqd** [TritonDataCenter/pkgsrc#255]
Please include latest XtraBackup 8.0.11, cause v2.4.18 is not able to make backups of MySQL 8. Thx!

**Comment by jperkin** [comment]
This is available in 2019Q4 for a customer, which release do you want it for?

**Comment by jfqd** [comment]
@jperkin for trunk, if possible :)

**Comment by jfqd** [comment]
@jperkin Thx a lot!
