### ISSUE TITLE
Packages missing in trunk after GCC 9.3.0 switch

### ISSUE THREAD

**Issue by jfqd** [TritonDataCenter/pkgsrc#258]
A list of packages missing currently in trunk:

* percona-server-8
* dnsdist
* elasticsearch
* beats
* proftpd-percona8
* pyzor

@jperkin: percona-server-8 is a big thing for us, cause we did a pkgin up and are now in a miserable state. If we would restart the percona server it will not find the (old) crypto libs (tested with another server before!). Linking new to old path does not fix it cause symbols are missing.

Would it be possible to get percona-server-8 back into trunk soon?

**Comment by jperkin** [comment]
I'll take a look through the list. While we always strive to ensure trunk is as stable as possible, these things happen when you're tracking the latest bits, and so I wouldn't necessarily recommend using it for critical things like database servers.  That said there are probably improvements I should make to pkgin to handle this kind of upgrade.

**Comment by jfqd** [comment]
@jperkin: getting percona-server-8 back would be great!

Just realized, that dtrace support vanished from percona-server-8? Was that removed by the build?

**Comment by jfqd** [comment]
Sorry for the noise. It is sad, but: [Support for DTrace is deprecated in MySQL 5.7 and is removed in MySQL 8.0.](https://dev.mysql.com/doc/refman/5.7/en/dba-dtrace-server.html)

**Comment by jperkin** [comment]
BTW, beats should be available? I updated it to a newer version a few days ago.

**Comment by jfqd** [comment]
Thx for beats. I saw it and today is test day for it :)

**Comment by jperkin** [comment]
All of these are now back except for dnsdist, I'll take a swing at that today.

**Comment by jfqd** [comment]
Wow, thanks @jperkin! That helps a lot!

**Comment by jfqd** [comment]
Thx, all packages are available now.
