### ISSUE TITLE
samba4 missing from pkgsrc trunk

### ISSUE THREAD

**Issue by zylantha** [TritonDataCenter/pkgsrc#262]
samba4 is not in the current pkgsrc trunk - only samba-3.6.25nb22 is visible.  Looks like it is failing to build?

https://bulktracker.appspot.com/pkg/ag1zfmJ1bGt0cmFja2VyciILEgVidWlsZBiAgICaj_uMCgwLEgNwa2cYgICAmuiK9gsM

**Comment by jperkin** [comment]
I fixed this a while back and `samba-4.12.3nb1` should now be available.
