### ISSUE TITLE
lang/ghc88: Increase disk space for Darwin bulk builds

### ISSUE THREAD

**Issue by Mitsos101** [TritonDataCenter/pkgsrc#264]
The build step for lang/ghc88 on all Darwin platforms fails with a "No space left on device" error on all of Joyent's bulk builds (otherwise, it fails with a "This package is known to stall the bulk build" error at the checksum step). Would the issue be remediated by increasing the available disk space for the build server? If so, are there any plans to do so?

**Comment by jperkin** [comment]
Ok, I'll take a look.  I disabled it as it ended up hanging the build, but perhaps that was related to the disk space issue.

**Comment by Mitsos101** [comment]
Hello @jperkin, any updates on this? It seems that there haven't been any attempts to build lang/ghc88 for Darwin on the pkgsrc-bulk mailing list.

**Comment by jperkin** [comment]
Oh sorry, I never got around to making this change.  I've done it now, it will take effect with the next builds.

**Comment by jperkin** [comment]
Looks like this is building correctly now according to the latest `macos15-trunk-x86_64` build.
