### ISSUE TITLE
Question: how to install SmartOS binary packages on non-Illumos operating system with pkgin

### ISSUE THREAD

**Issue by am11** [TritonDataCenter/pkgsrc#265]
> apologies in advance if it is already documented somewhere, but I could not find this information, therefore asking here directly.

On Debian/Linux system, in the path where [illumos/sysroot](https://github.com/illumos/sysroot) release tarball is restored, we want to install SmartOS binary packages. We have built pkgsrc tools (including pkgin) on Debian/Linux using pkgsrc (2020Q1) sources.

Now using this pkgin (<ins>Linux executable running on Debian/Linux system</ins>), is it possible to make it:

* fetch 2020 Q1/Q2 binary packages built <ins>for SmartOS</ins> and
* install package at location with <ins>custom path prefix</ins>

by, for example, modifying some config file or some command line switch? If so, how? :)

As an example, we compile FreeBSD's pkg tool (https://github.com/freebsd/pkg) on Debian/Linux, then modify its `pkg.conf` file to make it install FreeBSD packages on Debian/Linux inside the sysroot directory:

```sh
echo "ABI = \"FreeBSD:11:amd64\"; FINGERPRINTS = \"${__RootfsDir}/usr/share/keys\"; REPOS_DIR = [\"${__RootfsDir}/etc/pkg\"]; REPO_AUTOUPDATE = NO; RUN_SCRIPTS = NO;" > ${__RootfsDir}/usr/local/etc/pkg.conf
```

here `$__RootfsDir` is the root of where the sysroot files are restored. Complete working examples for various package managers and operating systems are available in this bash script: https://github.com/dotnet/arcade/blob/master/eng/common/cross/build-rootfs.sh.

**Comment by sjorge** [comment]
You might want to use pkg_add directly without going to pkgin, you should be able to specify most  stuff via env variables like PKG_PATH and such.

**Comment by jperkin** [comment]
TBH I'd go even more directly and just unpack the packages directly into wherever you want.  The `.tgz` files we ship are wrapped in `ar(1)` for the signing bits, but contain an unsigned package tarball that you can just unpack wherever.

Using `pkgin` or `pkg_install` is likely technically possible, but would end up just as ugly to work around the various `MACHINE_ARCH` checks etc as just doing it the tarball way.

**Comment by am11** [comment]
Thank you, I will try that approach. Is there an index page where binary packages are listed?

**Comment by am11** [comment]
Found it: https://pkgsrc.joyent.com/packages/SmartOS/2020Q1/x86_64/All/.
