### ISSUE TITLE
Please update zabbix to 4.0.20

### ISSUE THREAD

**Issue by jfqd** [TritonDataCenter/pkgsrc#269]
Would it be possible to get an update for zabbix? Latest for the 4.0 LTS branch is 4.0.20.

**Comment by jfqd** [comment]
@jperkin Ups zabbix vanished from trunk. Cause of the version update?

**Comment by jperkin** [comment]
This was updated in 9092c9dffcc3d73e4aeeb38ea772316cd34a68d4 and is now available in trunk.

**Comment by jfqd** [comment]
Thx a lot @jperkin!
