### ISSUE TITLE
Missing pure-ftpd in base-64-lts 19.4.0 ?

### ISSUE THREAD

**Issue by dca58** [TritonDataCenter/pkgsrc#270]
pure-ftpd used to be included in previous versions of base-64-lts images but not in the latest one.
Is it being abandoned or will it be added again later on ?

We use pure-ftpd on a number of machines, need to know if we should be looking for an alternative...

**Comment by jperkin** [comment]
It is failing in 2019Q4 due to incompatibilities against OpenSSL 1.1.  trunk has a newer release that fixes the OpenSSL issues but fails for other reasons.  I'll take a look.

**Comment by jperkin** [comment]
This is now fixed and available in 2019Q4.

**Comment by dca58** [comment]
Thanks a lot...
