### ISSUE TITLE
pkgin on Macos

### ISSUE THREAD

**Issue by imunitic** [TritonDataCenter/pkgsrc#275]
Just installed pkgsrc on my mac and here is what i get when i try to use it.

sudo pkgin up                                                                              Sat Jul 11 16:57:20 2020
Password:
processing remote summary (https://pkgsrc.joyent.com/packages/Darwin/trunk/x86_64/All)...
pkgin: Could not fetch https://pkgsrc.joyent.com/packages/Darwin/trunk/x86_64/All/pkg_summary.gz

I checked the url and sure enough pkg_summary.gz is not there.

Cheers, Ivica

**Comment by jperkin** [comment]
Oh that's bad timing, sorry. There's currently a rare issue with upgrades as per <https://twitter.com/jperkin/status/1281253912717262850> so I'm just waiting a few days for people to see that message or the one I posted to pkgsrc-users before allowing upgrades again.

Hopefully this won't put you off trying pkgsrc again in the next few days!  Whilst being a rolling-trunk release does mean that occasionally things might be a bit unstable I'm personally annoyed that I let this one happen, and it's very rare that things are broken like this.

**Comment by imunitic** [comment]
All is fine. I understand it completely. Will wait a couple of days and retry it.

**Comment by jperkin** [comment]
I'll post in this issue when the new bootstrap will be available.
