### ISSUE TITLE
[request] enabled tls-support for redis

### ISSUE THREAD

**Issue by jfqd** [TritonDataCenter/pkgsrc#279]
redis version >= 6 has [tls-support](https://redis.io/topics/encryption), but it need to be enabled at compile time (BUILD_TLS=yes).

Would it be possible to include this in one of the next builds?

**Comment by jperkin** [comment]
Added in https://github.com/NetBSD/pkgsrc/commit/e7e1b1a73c32fbd6609768feb0aa5ad604dfa177, this will turn up in the next trunk build.
