### ISSUE TITLE
Add Package for FRR

### ISSUE THREAD

**Issue by Smithx10** [TritonDataCenter/pkgsrc#28]
Quagga has been forked and now many people are using FRR (Free Range Routing).  Would be nice to have this working on SmartOS

Project Site: https://frrouting.org/ 
github-pkgsrc-url: https://github.com/FRRouting/frr/tree/master/pkgsrc 
gitbhub-solaris-build: https://github.com/FRRouting/frr/tree/master/solaris

**Comment by mamash** [comment]
Erronenous autoclose.
