### ISSUE TITLE
update py-barman 

### ISSUE THREAD

**Issue by Smithx10** [TritonDataCenter/pkgsrc#280]
https://github.com/joyent/pkgsrc/tree/trunk/databases/py-barman  Is currently at 2.5.

https://sourceforge.net/projects/pgbarman/files/2.11/  latest version is at 2.11

**Comment by jperkin** [comment]
Could you give this a spin and see if it works?  I'm able to run the commands at least to their help page so all of the dependencies should be correct, but don't have a working configuration to test actual workloads.

```
# pkg_add https://us-east.manta.joyent.com/pkgsrc/public/tmp/py37-barman-2.11.tgz
```

Thanks!

**Comment by jperkin** [comment]
Closing anyway, this was updated.
