### ISSUE TITLE
mosh-server needs libutempter

### ISSUE THREAD

**Issue by bahamat** [TritonDataCenter/pkgsrc#284]
Users logged in with mosh don't get added to utmpx due to missing libutempter. Illumos-gate recently added it, so SmartOS would get that automatically but to take advantage of it we'd need to up the minimum PI, which is probably a bit much for an issue affecting a single package.

Bringing our own should solve this problem.

**Comment by jperkin** [comment]
Everything is now in place, I'll push these changes to trunk later when the 2020Q3 builds have finished.  At least in my limited testing they all built correctly against libutempter, and the packages that I was able to test in a sandbox did start creating correct utmpx entries.

Will close this once the packages are available for wider testing.

**Comment by jperkin** [comment]
Ok these are now all available in trunk and 2020Q3, let me know if things don't work as expected.
