### ISSUE TITLE
unbound build fails due to include file issue and missing dependency

### ISSUE THREAD

**Issue by drboone** [TritonDataCenter/pkgsrc#286]
Preface: I'm very not clued in on pkgsrc practices.

The unbound build is currently failing for smartos-trunk.  I think there are two issues:

1. I can't find a dependency for nghttp2 (maybe I don't understand the makefile structure properly?).  Configure fails because its library and include files are not installed.  Adding a simple `DEPENDS+= nghttp2` line in the Makefile seems to address this error.  Not sure what the canonical packaging should look like here.

```
checking for libnghttp2... configure: error: Could not find libnghttp2, nghttp2.h
*** Error code 1

Stop.
bmake[1]: stopped in /data/jenkins/workspace/pkgsrc-upstream-trunk/net/unbound
*** Error code 1

Stop.
bmake: stopped in /data/jenkins/workspace/pkgsrc-upstream-trunk/net/unbound
```

2. services/listen_dnsport.c doesn't seem to include limits.h any way I can find, but the SSIZE_MAX definition is there.  Just adding a simple `#include <limits.h>` fixes that compile phase error.  Not sure if this should be wrapped in ifdefs or something.

```
--- listen_dnsport.lo ---
./services/listen_dnsport.c: In function 'http2_submit_response_read_callback':
./services/listen_dnsport.c:2129:15: error: 'SSIZE_MAX' undeclared (first use in this function); did you mean 'SIZE_MAX'?
 2129 |  if(copylen > SSIZE_MAX)
      |               ^~~~~~~~~
      |               SIZE_MAX
./services/listen_dnsport.c:2129:15: note: each undeclared identifier is reported only once for each function it appears in
*** [listen_dnsport.lo] Error code 1

bmake: stopped in /home/pbulk/build/net/unbound/work/unbound-1.12.0
```

Any chance you folks could turn the above notes into proper pkgsrc and implement?

**Comment by jperkin** [comment]
Hey, sorry I didn't respond to this ticket earlier, both of these issues have since been fixed and there should be a working unbound package available in trunk again.
