### ISSUE TITLE
Binary packages for Apple Silicon

### ISSUE THREAD

**Issue by pierrebeaucamp** [TritonDataCenter/pkgsrc#287]
Please excuse me if this is the wrong place for this request, but I'd be very interested in having binary packages for the new M1 Macs as well. It seems like a majority of packages compile just fine on the new machines, so hopefully that shouldn't be too big of a task. I'd also be happy to help out with the effort.

On a related note, there are a few packages that might benefit from being cross-compiled instead. Go (go115) comes to mind, as it cannot be bootstrapped on the new machines. I don't know if cross-compiled packages are usually included in the binary caches, so hopefully this is not an outrageous thing to ask.

Lastly, there seem to be some changes in Big Sur in regards to code-signing and I don't know if that is a potential issue to overcome before we can have binary caches. Given the fact that I couldn't find any related issue here talking about the new Apple processors, I thought it might at least make sense to have one tracking it.

**Comment by jperkin** [comment]
This is something we're hoping to produce soon, depending on when M1 hardware arrives.

I'm already producing Big Sur packages for Intel and there are no issues that I'm aware of with code-signing, so I'd assume the ARM systems would be the same.

**Comment by anoxic** [comment]
Hi, I'd love to see this as well. Just set up a Mini with an M1, if there's anything I can do to help let me know.

**Comment by jperkin** [comment]
Yeh sorry it's taking so long.  We've had hardware for a while, but unfortunately we're still waiting for someone to be able to physically go to it and disable SIP, and that's proving difficult with COVID restrictions.

We can't perform any builds until SIP is disabled, but as soon as that's done we should have packages soon after.

**Comment by anoxic** [comment]
That makes sense. I'm unable to compile pkgsrc manually for some reason (pkgtools/cwrapper is having an `No suitable Xcode SDK or Command Line Tools installed.` I'm guessing it's an old SDK dependency, but I haven't finished trying to figure out if there is already a fix for it in some other ticket elsewhere), so I'm just hoping it might happen more quickly, but I understand the pause.

**Comment by jperkin** [comment]
We've had arm64 packages available for a while now.
