### ISSUE TITLE
Clamav is too stale for freshclam updates on base-64-lts@18.4.0

### ISSUE THREAD

**Issue by gotwf** [TritonDataCenter/pkgsrc#298]
Latest stable version of clamav is 0.103.1 

Present pkg version is stuck back at clamav-0.99.4nb3:

> Currently, every version from ClamAV 0.99 and down, including all patch versions, are unsupported, and are actively blocked from downloading new updates.

EOL Policy:

https://www.clamav.net/documents/end-of-life-policy-eol

**Comment by jperkin** [comment]
Apologies that I didn't get to this at the time. 2018Q4 has been EOL for a while, and newer LTS and trunk have more recent releases. Will be looking to get the latest in prior to 2022Q4 being released.
