### ISSUE TITLE
ffmpeg not found in trunk

### ISSUE THREAD

**Issue by bahamas10** [TritonDataCenter/pkgsrc#301]
```
$ pkgin search ffmpeg
gst-ffmpeg-0.10.13nb23  GStreamer ffmpeg plugin

=: package is installed and up-to-date
<: package is installed but newer version is available
>: installed package has a greater version than available package
```

Is all I see.  I was able to compile it manually against the latest master branch with:

```
mkdir -p /var/tmp/ffmpeg
cd /var/tmp/ffmpeg
curl -L -o ffmpeg.tar.gz https://github.com/FFmpeg/FFmpeg/tarball/f7c3484b2659063043100e8194d5790d2aa1a73c
mkdir src
tar -xf ffmpeg.tar.gz -C src --strip-components=1
cd src

./configure --prefix=/opt/local --enable-libfdk-aac
make -j8
make install
```

---

**edit:** I should mention I had to install the following packages for this to compile:

```
pkgin install gcc9 pkg-config yasm fdk-aac
```

`fdk-aac` was something I needed for my own usage of `ffmpeg` FWIW

**Comment by jperkin** [comment]
Looks to be due to the libbluray update:

https://us-east.manta.joyent.com/pkgsrc/public/reports/trunk/x86_64/20210422.1237/libbluray-1.3.0nb1/build.log

Unfortunately we can't enable fdk-aac as it's a restricted license.

**Comment by bahamas10** [comment]
Ah interesting. And that's totally fine about `fdk-aac` - I don't personally mind having to custom compile it for that.  I just noticed `ffmpeg` was missing entirely and thought that was an issue worth bringing up.

**Comment by ghost** [comment]
Is there any update if or when ffmpeg will be back in the trunk?

**Comment by ghost** [comment]
I just got to update my system. Everything works again, thanks!

**Comment by jfqd** [comment]
@leonryrko Can you please close the issue?
