### ISSUE TITLE
samba not found in trunk

### ISSUE THREAD

**Issue by bahamas10** [TritonDataCenter/pkgsrc#303]
I checked this report:

https://us-east.manta.joyent.com/pkgsrc/public/reports/trunk/x86_64/20210422.1237/samba-3.6.25nb27/install.log

The tail of the log is:

```
=> Generating CTF data
=> Automatic stripping of debug information
=> Automatic manual page handling
=> Generating post-install file lists
=> Checking file-check results for samba-3.6.25nb27
ERROR: ************************************************************
ERROR: The following files are in /home/pbulk/build/net/samba/work/.destdir/opt/local but not in the PLIST:
ERROR:         /home/pbulk/build/net/samba/work/.destdir/opt/local/share/examples/samba/pam_smbpass/README
*** Error code 1

Stop.
bmake[1]: stopped in /data/jenkins/workspace/pkgsrc-trunk-x86_64/net/samba
*** Error code 1

Stop.
bmake: stopped in /data/jenkins/workspace/pkgsrc-trunk-x86_64/net/samba
```

If I understand this correctly, the package is building successfully - there is just a stray file (or files) that wasn't accounted for by the build process.

---

Side note: I've been switching a lot of my joyent/pkgsrc zones over to use trunk with the intention of simplifying my life and getting all of my zones on the same page.  Would you recommend using an LTS or a quarterly release instead?

**Comment by jperkin** [comment]
Oops, sorry, missed this ticket.  Samba has been in the required package list for a while now and so should always be available, and we're keeping 4.x up-to-date.  I'd recommend just running trunk unless there are specific reasons (e.g. a particular version of a package) you need to stick to an LTS.
