### ISSUE TITLE
Which pkgsrc branch are Joyent macOS binaries build from?

### ISSUE THREAD

**Issue by rnkn** [TritonDataCenter/pkgsrc#306]
Hey, thanks so much for hosting the Joyent macOS binaries.

Quick question, which branch are the binaries built from? I'm mixing pkgin binaries with packages built from source and not sure if I should be on this repo trunk or pkgsrc-2020Q4.

Thanks!

**Comment by jperkin** [comment]
They're always from trunk, but unfortunately have not been updated in a few months while we wait for the hardware to finish relocating to a new data centre, so there will be a large difference between the currently available packages and what you would build if using trunk.

Note though that mixing isn't a great idea, and will break badly if any of the package options differ between the binaries and source builds, especially if done in dependencies.

**Comment by rnkn** [comment]
Thanks for the quick reply! I'm using about 95% binaries, only building a few things with specific options, like ffmpeg, so I'm okay with the risks there.

Does NetBSD do their binaries like pkgsrc-YYYYQN?

**Comment by jperkin** [comment]
The official NetBSD package repositories use the quarterly branches, but mostly because they do not have the resources to track trunk.  FWIW I offer daily(-ish) package builds for NetBSD current from https://pkgsrc.joyent.com/install-on-netbsd/

**Comment by rnkn** [comment]
For macOS though I should stick with this repo's trunk HEAD, not NetBSD's?

**Comment by jperkin** [comment]
Yeh, the `joyent/release/macos` branch.
