### ISSUE TITLE
net/bind916 doesn't seem to exist, but I have it installed

### ISSUE THREAD

**Issue by dcarosone** [TritonDataCenter/pkgsrc#315]
Seem to be stuck unable to upgrade, binary fails to start because it's now missing an ldap .so

```shell
[root@ns ~]# pkgin list | grep ^bind
bind-9.16.7          Berkeley Internet Name Daemon implementation of DNS, version 9.14
[root@ns ~]# pkgin up && pkgin fug
processing remote summary (https://pkgsrc.joyent.com/packages/SmartOS/trunk/x86_64/All)...
database for https://pkgsrc.joyent.com/packages/SmartOS/trunk/x86_64/All is up-to-date
calculating dependencies...done.
nothing to do.
[root@ns ~]# pkgin se ^bind
bind-9.11.35 >       Berkeley Internet Name Daemon implementation of DNS, version 9.11
[...]
[root@ns ~]# uname -a
SunOS ns 5.11 joyent_20211021T215943Z i86pc i386 i86pc
```

Current trunk and PI, as shown.

What's going on?  I assume 9.16 is missing from a set list, and/or fails to build?  Do I just switch to 9.11?

**Comment by jperkin** [comment]
Yeh looks like it's currently failing:

https://us-east.manta.joyent.com/pkgsrc/public/reports/trunk/x86_64/20211022.1415/meta/report.html
https://us-east.manta.joyent.com/pkgsrc/public/reports/trunk/x86_64/20211022.1415/bind-9.16.21nb1/build.log

```
socket.c:5643:31: error: 'isc__socketmgr_t' undeclared (first use in this function); did you mean 'isc_socketmgr_t'?
```

This is coming from `patches/patch-lib_isc_unix_socket.c`.  I have no idea why this unknown type is being used.  Is this something that exists on native NetBSD or something?

I'm not keen on how many patches are being applied to this package, but I can look at fixing it and adding it to the required packages list.  For now it might be better to revert back to 9.11 temporarily.

**Comment by jperkin** [comment]
To start with I've put a shout out for someone who maintains the patchset to take a look: https://mail-index.netbsd.org/pkgsrc-users/2021/10/23/msg034610.html

**Comment by jperkin** [comment]
bind-9.16 is in the list of required packages (so we get notified if it goes missing, and publishing is disabled for that build), and has been available for a while now.
