### ISSUE TITLE
Oldish gitea package in base-64-lts 21.4.0

### ISSUE THREAD

**Issue by dca58** [TritonDataCenter/pkgsrc#321]
The package in base-64-lts 21.4.0 is gitea-1.13.4nb13.tgz but 1.15 was released last summer and 1.16 a few day ago.
It would be great to have one of these as significant improvements were introduced in 1.15.

Kind regards

**Comment by jperkin** [comment]
Is it something you would consider being maintainer for?  The current maintainer hasn't been active for quite a while.

**Comment by dca58** [comment]
I don't have enough time currently, sorry...

**Comment by drscream** [comment]
I will have a look, but the commit will be for trunk. So maybe @jperkin like to backport it later ;-)

**Comment by dca58** [comment]
Is there a good, up to date, tutorial or blog entry to get started building packages for SmartOS ?

**Comment by drscream** [comment]
The latest `gitea` version has been pushed into `trunk` you can find more details in the [pkgsrc-changes list](https://mail-index.netbsd.org/pkgsrc-changes/2022/02/16/msg249351.html). Additional to that a binary package could be found for the 2021Q4 branch at[skylime-extra](https://pkgsrc.smartos.skylime.net/skylime-extra/2021Q4/x86_64/).

Additional to your second question, have a look at in the [wiki](https://github.com/joyent/pkgsrc/wiki).

**Comment by dca58** [comment]
Thanks a lot for this !
I wanted to give it a try but failed to install it ("pkg_add: unable to verify signature: Signature key id 4c5fa701f7d8ac9b not found").
I try to play with VERIFIED_INSTALLATION=trusted or never but it didn't help.
Thanks anyway

**Comment by drscream** [comment]
Yea sorry, our packages are signed by SkyLime. You can find an GPG key file which contains the Joyent and SkyLime public key here: https://github.com/skylime/mi-core-base/blob/master/copy/opt/local/etc/gnupg/pkgsrc.gpg

(Backup and) replace the existing `/opt/local/etc/gnupg/pkgsrc.gpg` with the file you downloaded.

**Comment by dca58** [comment]
That helps a lot, thanks again !

**Comment by jperkin** [comment]
gitea 1.16.8 is in trunk, and we can look at updating to the latest version prior to 2022Q4 being branched.
