### ISSUE TITLE
openjdk17 availability ?

### ISSUE THREAD

**Issue by dca58** [TritonDataCenter/pkgsrc#325]
The latest available OpenJDK is openjdk11, is it foreseen to have a openjdk17 (LTS) at some point ?
Is yes, an approximate timeframe would be great...
Thanks a lot

**Comment by jperkin** [comment]
I don't know.  Oracle dropped support for Solaris, and while ptribble and others have done a great job resurrecting patches, it's clear that it will always be a massive uphill struggle from now on to continue supporting newer versions, and will only get more difficult as time goes on.

Ultimately it will depend on volunteers who care enough to do the work in the first place, and then continue to maintain it.

**Comment by jperkin** [comment]
I forgot to mention that an openjdk17 package has been available in trunk for a little while now.
