### ISSUE TITLE
DHCP server packages missing or broken

### ISSUE THREAD

**Issue by moenoel** [TritonDataCenter/pkgsrc#328]
The package `isc-dhcpd` that previously existed is missing (but `isc-dhcp` is still there), which breaks existing installs when updating.

An alternative seems to be `kea`, but that is missing an SMF manifest and also its management scripts are broken, as they don't work with `/bin/sh` on SmartOS.

Would love if either or both of these could be fixed.

**Comment by jperkin** [comment]
Thanks for the heads up, I've fixed the `isc-dhcpd` package and it should show up in the next push.

**Comment by moenoel** [comment]
Thank you. Do you have an ETA for when the package will be available again?

Also, just for the record, in case anyone wants to look at the `kea` package in future for some reason: There are several more broken aspects about it. The management script `keactrl` uses `basename -- <stuff>`, which doesn't work with SmartOS' `/usr/bin/basename`. It also wants to access `/dev/bpf0` which seems to be `/dev/bpf` instead on SmartOS.

**Comment by jperkin** [comment]
It'll be in the build after the one that is currently executing, so my guess would be possibly later tomorrow.

**Comment by jperkin** [comment]
This is now available.
