### ISSUE TITLE
MySQL and Percona Server 8 are missing

### ISSUE THREAD

**Issue by jfqd** [TritonDataCenter/pkgsrc#332]
MySQL and Percona Server 8 are missing in trunk. Latest version is 8.0.29 vor MySQL an 8.0.27 for Percona Server.

**Comment by jfqd** [comment]
@jperkin Thx for bringing Percona Server 8 back to trunk. Start crashes with "abort_handler_s: memset_s: s is NULL" error.

```
2022-05-12T08:00:08.039932Z 0 [System] [MY-010116] [Server] /opt/local/sbin/mysqld (mysqld 8.0.27-18) starting as process 82277
2022-05-12T08:00:08.077063Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2022-05-12T08:00:10.999185Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
abort_handler_s: memset_s: s is NULL
```

Do you have any idea what the issue might be?

**Comment by jfqd** [comment]
Tested it in a lx-zone with ubuntu 20.04 and the apt-repo from percona. No abort-notice on our databases.
So this must be an issue of the new compiled version of percona-server 8 in trunk.

We need mysql-server 8 or percona-server 8 cause of features mariadb is missing. So migrating over to mariadb is no option for us :/

**Comment by jfqd** [comment]
Tried the latest build from two days ago, but it still has the same issues.

**Comment by jperkin** [comment]
Can I just check that you're using the latest versions available in the repository?  They'll be available via a refresh rather than a version bump.

I'm trying to reproduce this but failing so far.  The test suite is showing some failures, but overall is running the server fine and passing the vast majority of tests.

If it's still failing for you then if there's a way you can get a reproducible test case that'd be really helpful, or at least a backtrace so I can figure out which `memset_s` call is triggering the problem.

Thanks!

**Comment by jperkin** [comment]
Just for the record:

```
The servers were restarted 209 times
The servers were reinitialized 11 times
Spent 3074.319 of 1191 seconds executing testcases

Too many failed: Failed 10/945 tests, 98.94% were successful.

Failing test(s): main.partition_prefixkey_upgrade main.gis main.myisam_explain_json_non_select_all main.ssl_san main.myisam_explain_json_non_select_none main.resource_group_binlog_events main.dd_upgrade_partition main.gis-precise main.resource_group_thr_prio_unsupported main.dd_upgrade_non_debug
```

```
$ grep -r abort_handler /home/pbulk/build/joyent/percona80-server/work/build/mysql-test/var/log/
$
```

**Comment by jfqd** [comment]
@jperkin Sorry for the delay in answering. Tried the latest version on three instances. Two are running smoothly, but one instance is eroding all ram of the zone. Every two hours the ram was exhausted. Switched to mariadb for this zone cause of the issue. Sorry but I was not able to find the reason of the eroding ram issue.

Mariadb is ok for this zone, but for our main mysql cluster we depend on mysql/persona. We are running the cluster now on lx cause of the reported issue.

**Comment by jperkin** [comment]
I updated mysql80-* to 8.0.31 and they're now available in trunk.
