### ISSUE TITLE
Zabbix 6.0 LTS

### ISSUE THREAD

**Issue by dca58** [TritonDataCenter/pkgsrc#334]
But the available version in pkgin is still zabbix-4.0.24nb6, an update on the latest LTS image would be appreciated...
Kind regards

**Comment by dca58** [comment]
I see that a Zabbix 6.0 package is available on OmniOS, which may be an indication that there is no Illumos incompatibility.

**Comment by jperkin** [comment]
There are zabbix 6.0 packages available in trunk:

```console
$ pkgin avail | grep zabbix.*6.0.14
zabbix-agent-6.0.14  Enterprise-class Monitoring Solution for Everyone
zabbix-frontend-postgresql-6.0.14 Zabbix PHP 8 frontend
zabbix-java-6.0.14nb1 Enterprise-class Monitoring Solution for Everyone
zabbix-proxy-postgresql-6.0.14 Enterprise-class Monitoring Solution for Everyone
zabbix-server-postgresql-6.0.14 Enterprise-class Monitoring Solution for Everyone
```

Are you able to give these a go and let me know if they work ok? If LTS is a blocker for you then I may be able to backport them to 2022Q4.
