### ISSUE TITLE
opendkim missing from SmartOS/trunk

### ISSUE THREAD

**Issue by russhan** [TritonDataCenter/pkgsrc#335]
opendkim is missing from SmartOS/trunk.  My best guess is it appears to be due to a hiccup with libmilter.

https://us-east.manta.joyent.com/pkgsrc/public/reports/trunk/x86_64/20220514.1357/opendkim-2.10.3nb8/depends.log
```
The PKG_SKIP_SMF variable was set or automatic import of SMF manifests
failed.  You must import the SMF manifest manually with:

	/usr/sbin/svccfg import /opt/local/lib/svc/manifest/libmilter.xml
```

https://us-east.manta.joyent.com/pkgsrc/public/reports/trunk/x86_64/20220514.1357/opendkim-2.10.3nb8/configure.log
```
=> Build dependency libmilter>=8.14: found libmilter-8.16.1nb1
[...]
configure: error: libmilter not found
```

**Comment by jperkin** [comment]
I think this came in just before I'd already fixed it, it should be available now.
