### ISSUE TITLE
Point to https://pkgsrc.smartos.org

### ISSUE THREAD

**Issue by papertigers** [TritonDataCenter/pkgsrc#337]
The GitHub slug still lists http://pkgsrc.joyent.com

The pkgsrc.smartos.org page also doesn't seem to have a valid SSL certificate.

**Comment by jperkin** [comment]
Yeh, pkgsrc.smartos.org is still set up as the old 2013 site.  I'll be migrating it over to MNX soon.

**Comment by jperkin** [comment]
I did this a while back.
