### ISSUE TITLE
Expired cert error for pkgsrc.joyent.com

### ISSUE THREAD

**Issue by mthalman** [TritonDataCenter/pkgsrc#342]
From build log:

```
--2022-09-06 14:06:09--  https://pkgsrc.joyent.com/packages/SmartOS/trunk/x86_64/All
Resolving pkgsrc.joyent.com (pkgsrc.joyent.com)... 64.30.129.74
Connecting to pkgsrc.joyent.com (pkgsrc.joyent.com)|64.30.129.74|:443... connected.
ERROR: cannot verify pkgsrc.joyent.com's certificate, issued by ‘CN=R3,O=Let's Encrypt,C=US’:
  Issued certificate has expired.
```

From browser:

![image](https://user-images.githubusercontent.com/15789599/188659407-6be233db-5718-417f-8c40-0ec2f9c47c82.png)

**Comment by jperkin** [comment]
Thanks, this was supposed to have been migrated to pkgsrc.smartos.org last Friday but got delayed.  I've renewed the cert for now, but you should really be updating your repositories to pkgsrc.smartos.org as per https://smartos.topicbox.com/groups/smartos-discuss/Tc0914fe1414685b5-M516296004a2f8ea793b60932 anyway, as you'll get PGP errors after the CNAME switch if you haven't imported the new key.
