### ISSUE TITLE
dnsdist missing in trunk

### ISSUE THREAD

**Issue by jfqd** [TritonDataCenter/pkgsrc#344]
Cannot find **dnsdist** in trunk. Is it gone? In the latest list of build failures I cannot find it either.

**Comment by jperkin** [comment]
https://us-central.manta.mnx.io/pkgsrc/public/reports/trunk/x86_64/20221001.2023/meta/report.html
https://us-central.manta.mnx.io/pkgsrc/public/reports/trunk/x86_64/20221001.2023/dnsdist-1.5.1nb3/install.log

I'll fix this today.

**Comment by jfqd** [comment]
@ jperkin Thx a lot! newer dnsdig does not have a ```-d``` flag any more, so an additional method file is needed, see:

https://github.com/jfqd/mi-qutic-pdns/blob/master/copy/opt/local/lib/svc/manifest/dnsdist.xml
https://github.com/jfqd/mi-qutic-pdns/blob/master/copy/opt/local/lib/svc/method/dnsdist

**Comment by jfqd** [comment]
@jperkin Were there any issues building dnsdig?

**Comment by jperkin** [comment]
I've updated dnsdist to 1.7.2 in trunk, it'll hopefully appear in the next build.  I'll leave this open until then.

**Comment by jperkin** [comment]
1.7.2 is now available.

**Comment by jfqd** [comment]
@jperkin thank you for the updated package. But the smf has an issue, the dnsdist process restarts every time. You may use an additional method file to get it nicely working:

https://github.com/jfqd/mi-qutic-pdns/blob/master/copy/opt/local/lib/svc/manifest/dnsdist.xml
https://github.com/jfqd/mi-qutic-pdns/blob/master/copy/opt/local/lib/svc/method/dnsdist

**Comment by jfqd** [comment]
@jperkin I cannot open this ticket, maybe you can open it again?

**Comment by jperkin** [comment]
Sorry, I finally got around to this, fixed in 3675f5dbadbda416fa35d8331e7c60cc10a13f0e.

**Comment by jfqd** [comment]
@jperkin Thx for fixing it! The [method](https://github.com/jfqd/mi-qutic-pdns/blob/master/copy/opt/local/lib/svc/method/dnsdist) file is not really needed, it was more a convenient thing for me :)
