### ISSUE TITLE
HexChat gone?

### ISSUE THREAD

**Issue by danielktdoranie** [TritonDataCenter/pkgsrc#345]
I was able to install HexChat using pkgsrc on my MacBook Air (M1, 2020) running macOS Monterey 12.6 (21G115)... I did reinstall of the OS and now I get this when I try to install HexChat:

```
danieldoran@Daniels-MacBook-Air ~ % sudo pkgin -y install hexchat
hexchat is not available in the repository
calculating dependencies...done.
nothing to do.
danieldoran@Daniels-MacBook-Air ~ %`

```
Was it removed from the repository?

**Comment by jperkin** [comment]
I'll add this to the list of required packages and make sure it's in the next build.

**Comment by danielktdoranie** [comment]
> I'll add this to the list of required packages and make sure it's in the next build.

Thank you!

**Comment by jperkin** [comment]
hexchat is now available again.
