### ISSUE TITLE
mariadb fails to start: configured pid file location does not exist

### ISSUE THREAD

**Issue by drboone** [TritonDataCenter/pkgsrc#346]
The supplied method script specifies a pid file location in a directory that does not exist, /var/run/mariadb.  The method script cannot create the directory because it is already running as mariadb.  For mysql, it looks like the approach taken was to place the pid file in /var/mysql, where the daemon does have write access.

**Comment by drboone** [comment]
Worse and furthermore, the pid file location hard coded in the method script causes mariadb to ignore a `pid_file=/x/y` directive in its config file.

**Comment by jperkin** [comment]
Sorry I missed this! Will get it fixed on Monday and backport to 2022Q4.

**Comment by jperkin** [comment]
Thanks, fixed in 9d5bb663ae7bac198181604cd9dffdbd38a69e15
