### ISSUE TITLE
SMF method script for bind looks in the wrong place for rndc-confgen

### ISSUE THREAD

**Issue by drboone** [TritonDataCenter/pkgsrc#35]
bind 9.10
pkgin 0.9.4 for SunOS-5.11 x86_64 (using SQLite 3.20.1)
platform 20170916T185915Z

The path /usr/sbin/rndc-confgen is hardcoded, but the package installs the binary in /opt/local/sbin.

**Comment by jperkin** [comment]
Fixed in https://github.com/NetBSD/pkgsrc/commit/9dd4b0a4ef8949f5f229f933524cd7494bcc0af5, thanks!
