### ISSUE TITLE
lang/go does not set GOOS variable to "illumos"

### ISSUE THREAD

**Issue by bardo** [TritonDataCenter/pkgsrc#350]
Some Go packages fail to build due to the `GOOS` variable being unset, which makes Go default to a Solaris build:

```
go env | grep -E 'GO(ARCH|OS)'
GOARCH="amd64"
GOOS="solaris"
```

The `illumos` target was introduced with https://github.com/golang/go/issues/20603, and it should probably be set in `lang/go/version.mk`.

**Comment by jperkin** [comment]
Yeh I was working on this before the Christmas break, and it will be switched for the 2022Q4 release.

**Comment by jperkin** [comment]
2022Q4 included this change, and I merged it into trunk in https://github.com/NetBSD/pkgsrc/commit/428ecfe1486baa569db8744bb050428bd7a56951 once I was happy with the results.
