### ISSUE TITLE
 Support for Mac OS 10.15 (Catalina)

### ISSUE THREAD

**Issue by Meilenstein** [TritonDataCenter/pkgsrc#351]
On the website only upgrades for 11.3+ is mentioned, but 10.15 is missing in the list of archives of the previous package sets.
Or is it still supported? (packages in the folder trunk are from 2022)

**Comment by jperkin** [comment]
I never produced a dedicated set for Catalina (by far the most unstable macOS release in recent years), but the archived Mojave set should work absolutely fine.
