### ISSUE TITLE
Cloudflare cfssl binaries

### ISSUE THREAD

**Issue by nheimlich** [TritonDataCenter/pkgsrc#354]
The following binaries are missing from pkgsrc: cfssl, cfssljson
[CFSSL: Cloudflare's PKI and TLS toolkit](https://github.com/cloudflare/cfssl)
It appears this is already available within [pkgsrc-wip](https://github.com/TritonDataCenter/pkgsrc-wip/tree/master/cfssl)

I was able to build using gmake-4.4, go-1.19.4, gcc12 on `base-64-lts 22.4.0`

I am willing to participate in helping get these packages added.

**Comment by jperkin** [comment]
I've imported the wip package (with a couple of minor changes) in 4f7945f7de9ac7501b8ff284e1c482185c86903d, so this will appear in the next trunk build.

I'll close this ticket out when the package is available.

**Comment by jperkin** [comment]
This is now available:

```
$ pkgin se cfssl
cfssl-1.6.3          CloudFlare PKI toolkit
```
