### ISSUE TITLE
Is it possible to configure a proxy for pkgin

### ISSUE THREAD

**Issue by zssfred** [TritonDataCenter/pkgsrc#358]
From my site, the connection to smartos.org/package is so poor..

Thanks.

Fred

**Comment by jperkin** [comment]
Yes, we provide an rsync service at rsync://pkgsrc.smartos.org/ where you can mirror package sets, serve them up using your preferred web server, and you can then configure your pkgin `repositories.conf` to point to it instead of https://pkgsrc.smartos.org/

**Comment by zssfred** [comment]
gotcha.

Thank you!
