### ISSUE TITLE
wireshark failed on DilOS

### ISSUE THREAD

**Issue by ikozhukhov** [TritonDataCenter/pkgsrc#36]
DilOS iso:
http://apt2.dilos.org/dilos/isos/dilos-core-17-10-31_16-39-2.0.0.6.iso

installed pkgsrc:
https://pkgsrc.joyent.com/packages/SmartOS/bootstrap/bootstrap-2017Q3-x86_64.tar.gz

install wireshark by:
/opt/local/bin/pkgin in xterm xauth wireshark

try to start wireshark by and has core.

root@dilos-init11:~# /opt/local/bin/wireshark-gtk 
Arithmetic Exception (core dumped)

root@dilos-init11:~# mdb core
Loading modules: [ libumem.so.1 libc.so.1 libnvpair.so.1 libuutil.so.1 libavl.so.1 ld.so.1 ]
> $C
fffffd7fffdff720 bytes_view_adjustment_set+0x8d()
fffffd7fffdff780 bytes_view_adjustment_set+0x195()
fffffd7fffdff860 libgobject-2.0.so.0.5200.3`g_object_new_internal+0x6f1()
fffffd7fffdff8d0 libgobject-2.0.so.0.5200.3`g_object_newv+0x27d()
fffffd7fffdff9d0 libgobject-2.0.so.0.5200.3`g_object_new+0x10c()
fffffd7fffdff9e0 bytes_view_new+0x15()
fffffd7fffdffa40 add_byte_tab+0x84()
fffffd7fffdffa60 byte_view_new+0x83()
fffffd7fffdffbb0 main+0x8bd()
fffffd7fffdffbc0 _start+0x6c()

root@dilos-init11:/opt/local/bin# ldd wireshark-gtk 
        libwscodecs.so.1 =>      /opt/local/lib//libwscodecs.so.1
        libwiretap.so.6 =>       /opt/local/lib//libwiretap.so.6
        libwireshark.so.8 =>     /opt/local/lib//libwireshark.so.8
        liblua5.2.so.5 =>        /opt/local/lib//liblua5.2.so.5
        libdl.so.1 =>    /lib/64/libdl.so.1
        libwsutil.so.7 =>        /opt/local/lib//libwsutil.so.7
        libcrypto.so.1.0.0 =>    /opt/local/lib//libcrypto.so.1.0.0
        libpcap.so.0 =>  /opt/local/lib//libpcap.so.0
        libdlpi.so.1 =>  /lib/64/libdlpi.so.1
        libkrb5.so.3 =>  /opt/local/lib//libkrb5.so.3
        libk5crypto.so.3 =>      /opt/local/lib//libk5crypto.so.3
        libcom_err.so.3 =>       /opt/local/lib//libcom_err.so.3
        libkrb5support.so.0 =>   /opt/local/lib//libkrb5support.so.0
        libgcrypt.so.20 =>       /opt/local/lib//libgcrypt.so.20
        libgpg-error.so.0 =>     /opt/local/lib//libgpg-error.so.0
        libgnutls.so.30 =>       /opt/local/lib//libgnutls.so.30
        libunistring.so.2 =>     /opt/local/lib//libunistring.so.2
        libtasn1.so.6 =>         /opt/local/lib//libtasn1.so.6
        libhogweed.so.4 =>       /opt/local/lib//libhogweed.so.4
        libnettle.so.6 =>        /opt/local/lib//libnettle.so.6
        libgmp.so.10 =>  /opt/local/lib//libgmp.so.10
        libgen.so.1 =>   /lib/64/libgen.so.1
        libsmi.so.2 =>   /opt/local/lib//libsmi.so.2
        libgtk-3.so.0 =>         /opt/local/lib//libgtk-3.so.0
        libgdk-3.so.0 =>         /opt/local/lib//libgdk-3.so.0
        libpangocairo-1.0.so.0 =>        /opt/local/lib//libpangocairo-1.0.so.0
        libpangoft2-1.0.so.0 =>  /opt/local/lib//libpangoft2-1.0.so.0
        libharfbuzz.so.0 =>      /opt/local/lib//libharfbuzz.so.0
        libpango-1.0.so.0 =>     /opt/local/lib//libpango-1.0.so.0
        libatk-1.0.so.0 =>       /opt/local/lib//libatk-1.0.so.0
        libcairo-gobject.so.2 =>         /opt/local/lib//libcairo-gobject.so.2
        libcairo.so.2 =>         /opt/local/lib//libcairo.so.2
        libpixman-1.so.0 =>      /opt/local/lib//libpixman-1.so.0
        libfontconfig.so.1 =>    /opt/local/lib//libfontconfig.so.1
        libexpat.so.1 =>         /opt/local/lib//libexpat.so.1
        libfreetype.so.6 =>      /opt/local/lib//libfreetype.so.6
        libbz2.so.0 =>   /opt/local/lib//libbz2.so.0
        libxcb-shm.so.0 =>       /opt/local/lib//libxcb-shm.so.0
        libxcb-render.so.0 =>    /opt/local/lib//libxcb-render.so.0
        libXrender.so.1 =>       /opt/local/lib//libXrender.so.1
        libXext.so.0 =>  /opt/local/lib//libXext.so.0
        libX11.so.6 =>   /opt/local/lib//libX11.so.6
        libxcb.so.1 =>   /opt/local/lib//libxcb.so.1
        libXau.so.6 =>   /opt/local/lib//libXau.so.6
        libXdmcp.so.6 =>         /opt/local/lib//libXdmcp.so.6
        librt.so.1 =>    /lib/64/librt.so.1
        libgdk_pixbuf-2.0.so.0 =>        /opt/local/lib//libgdk_pixbuf-2.0.so.0
        libpng16.so.16 =>        /opt/local/lib//libpng16.so.16
        libgio-2.0.so.0 =>       /opt/local/lib//libgio-2.0.so.0
        libresolv.so.2 =>        /lib/64/libresolv.so.2
        libgobject-2.0.so.0 =>   /opt/local/lib//libgobject-2.0.so.0
        libffi.so.6 =>   /opt/local/lib//libffi.so.6
        libgthread-2.0.so.0 =>   /opt/local/lib//libgthread-2.0.so.0
        libgmodule-2.0.so.0 =>   /opt/local/lib//libgmodule-2.0.so.0
        libglib-2.0.so.0 =>      /opt/local/lib//libglib-2.0.so.0
        libpcre.so.1 =>  /opt/local/lib//libpcre.so.1
        libpthread.so.1 =>       /lib/64/libpthread.so.1
        libthread.so.1 =>        /lib/64/libthread.so.1
        libnsl.so.1 =>   /lib/64/libnsl.so.1
        libsocket.so.1 =>        /lib/64/libsocket.so.1
        libintl.so.8 =>  /opt/local/lib//libintl.so.8
        libiconv.so.2 =>         /opt/local/lib//libiconv.so.2
        libc.so.1 =>     /lib/64/libc.so.1
        libz.so.1 =>     /opt/local/lib//libz.so.1
        libm.so.2 =>     /lib/64/libm.so.2
        libumem.so.1 =>  /lib/64/libumem.so.1
        libssp.so.0 =>   /opt/local/gcc49/x86_64-sun-solaris2.11/lib/amd64/libssp.so.0
        libgcc_s.so.1 =>         /opt/local/gcc49/x86_64-sun-solaris2.11/lib/amd64/libgcc_s.so.1
        libinetutil.so.1 =>      /lib/64/libinetutil.so.1
        libdladm.so.1 =>         /lib/64/libdladm.so.1
        libXinerama.so.1 =>      /opt/local/lib//libXinerama.so.1
        libXrandr.so.2 =>        /opt/local/lib//libXrandr.so.2
        libXcursor.so.1 =>       /opt/local/lib//libXcursor.so.1
        libXcomposite.so.1 =>    /opt/local/lib//libXcomposite.so.1
        libXdamage.so.1 =>       /opt/local/lib//libXdamage.so.1
        libXfixes.so.3 =>        /opt/local/lib//libXfixes.so.3
        libatk-bridge-2.0.so.0 =>        /opt/local/lib//libatk-bridge-2.0.so.0
        libatspi.so.0 =>         /opt/local/lib//libatspi.so.0
        libXtst.so.6 =>  /opt/local/lib//libXtst.so.6
        libXi.so.6 =>    /opt/local/lib//libXi.so.6
        libxkbcommon-x11.so.0 =>         /opt/local/lib//libxkbcommon-x11.so.0
        libxcb-xkb.so.1 =>       /opt/local/lib//libxcb-xkb.so.1
        libxkbcommon.so.0 =>     /opt/local/lib//libxkbcommon.so.0
        libdbus-1.so.3 =>        /opt/local/lib//libdbus-1.so.3
        libbsm.so.1 =>   /lib/64/libbsm.so.1
        libepoxy.so.0 =>         /opt/local/lib//libepoxy.so.0
        libmd.so.1 =>    /lib/64/libmd.so.1
        libmp.so.2 =>    /lib/64/libmp.so.2
        libdevinfo.so.1 =>       /lib/64/libdevinfo.so.1
        libscf.so.1 =>   /lib/64/libscf.so.1
        librcm.so.1 =>   /lib/64/librcm.so.1
        libnvpair.so.1 =>        /lib/64/libnvpair.so.1
        libexacct.so.1 =>        /usr/lib/64/libexacct.so.1
        libkstat.so.1 =>         /lib/64/libkstat.so.1
        libpool.so.1 =>  /usr/lib/64/libpool.so.1
        libvarpd.so.1 =>         /usr/lib/64/libvarpd.so.1
        libsecdb.so.1 =>         /lib/64/libsecdb.so.1
        libtsol.so.2 =>  /lib/64/libtsol.so.2
        libsec.so.1 =>   /lib/64/libsec.so.1
        libuutil.so.1 =>         /lib/64/libuutil.so.1
        libsmbios.so.1 =>        /usr/lib/64/libsmbios.so.1
        libxml2.so.2 =>  /lib/64/libxml2.so.2
        libavl.so.1 =>   /lib/64/libavl.so.1
        libidspace.so.1 =>       /usr/lib/64/libidspace.so.1
        libmd5.so.1 =>   /lib/64/libmd5.so.1
        librename.so.1 =>        /usr/lib/64/librename.so.1
        libbunyan.so.1 =>        /usr/lib/64/libbunyan.so.1
        libidmap.so.1 =>         /usr/lib/64/libidmap.so.1
        libz.so.1 =>     /lib/64/libz.so.1
        liblzma.so.5 =>  /lib/64/liblzma.so.5
        libiconv.so.2 =>         /lib/64/libiconv.so.2
        libofmt.so.1 =>  /lib/64/libofmt.so.1

**Comment by jperkin** [comment]
I tested wireshark in 2018Q2 and it appeared to work fine (seen in https://pkgsrc.joyent.com/img/illumos-desktop-2018Q2.png), so will close this out for now.
