### ISSUE TITLE
Various nagios-* packages missing in trunk

### ISSUE THREAD

**Issue by moenoel** [TritonDataCenter/pkgsrc#362]
Various Nagios related packages seem to have gone missing in trunk that are present in 2022Q4, including `nagios-base`, `nagios-plugins` and various `nagios-plugin-*` ones. Would it be possible for them to be re-added?

**Comment by jperkin** [comment]
Sure I'll take a look. These have been updated to newer versions since 2022Q4 but there appear to be some basic programming errors in them causing them to fail.

**Comment by jperkin** [comment]
I've updated both sets of packages to the latest and fixed build issues in https://github.com/TritonDataCenter/pkgsrc/commit/650bdb3caab13386e7272572496d3e78898314d6 and https://github.com/TritonDataCenter/pkgsrc/commit/fb09e34f48f68e1b694e88614d2cb47984a62955

These have been pushed and I'll close the ticket out once binaries have been published from the current build.

**Comment by moenoel** [comment]
Awesome. Thank you very much.

**Comment by jperkin** [comment]
These are now available:

```console
$ pkgin se ^nagios
nagios-base-4.4.10   Network monitor
nagios-nrpe-3.2.0nb7  Nagios remote program execution daemon
nagios-nsca-2.9.1nb10  Remote/passive network service for nagios
nagios-plugin-dotpid-0.7  /var/run/*.pid monitoring plugin for Nagios
nagios-plugin-ldap-2.4.3  Nagios ldap plugin
nagios-plugin-mysql-2.4.3  Nagios mysql plugin
nagios-plugin-mysqlslave-0.2nb2  MySQL and MariaDB slave monitoring plugin for Nagios
nagios-plugin-pgsql-2.4.3  Nagios pgsql plugin
nagios-plugin-printer-0.0.363nb3  Gather supply metrics from a printer via SNMP query
nagios-plugin-radius-2.4.3  Nagios radius plugin
nagios-plugin-snmp-2.4.3  Nagios snmp plugins
nagios-plugin-snmp_environment-0.7nb3  Check various hardware environmental sensors
nagios-plugin-spamd-1.6.0nb9  Nagios plugin for monitoring the SpamAssassin daemon
nagios-plugin-syncrepl-0.5nb1  LDAP replication monitoring plugin for Nagios
nagios-plugins-2.4.3  Nagios plugins
```
