### ISSUE TITLE
public signing key for packages

### ISSUE THREAD

**Issue by gszr** [TritonDataCenter/pkgsrc#373]
Is the public signing key used to sign the Linux packages available somewhere other than the bootstrap tarball?

**Comment by jperkin** [comment]
Yes, they are available from https://pkgsrc.smartos.org/pgp/

**Comment by gszr** [comment]
> Yes, they are available from [pkgsrc.smartos.org/pgp](https://pkgsrc.smartos.org/pgp/)

Thank you!

**Comment by gszr** [comment]
@jperkin would it be desirable to add a link to https://pkgsrc.smartos.org/install-on-linux/ - as an alternative to downloading the entire bootstrap file? I can get a PR together if you point me to where.

**Comment by jperkin** [comment]
There's already a link in the commented-out GPG instructions.
