### ISSUE TITLE
cyrus-sasl wrong plugin dir configuration

### ISSUE THREAD

**Issue by xmerlin** [TritonDataCenter/pkgsrc#378]
In your message, you have indicated ${PLUGINDIR} as the default path for plugin modules, but this is incorrect. 

Actually, Cyrus-SASL searches for configuration files like smtpd.conf in /opt/local/etc/sasl2/

**Comment by jperkin** [comment]
I think it's correct, though perhaps the wording could do with some work.  For the configuration file it says:

```
The configuration files for applications using the sasl2 libraries
used to be in ${PLUGINDIR}/, but are now expected in
${PKG_SYSCONFDIR}/. You need to move them after upgrading the pkg.
```

The modules themselves definitely live in `${PLUGINDIR}`, so the other part of the MESSAGE also seems correct:

```
${PKGNAME} will use the following directory as the default
path to its plugin modules:

        ${PLUGINDIR}

The search path for plugin modules can be customized by setting the
SASL_PATH variable to a colon-delimted list of directories in the shell
environment.
```

I'm generally against MESSAGE files as they often aren't helpful, and I wonder if this one is causing more problems than it helps, even though it's technically correct.

**Comment by xmerlin** [comment]
In theory, it is correct; in practice, it gives the user a wrong and misleading indication since the file needs to be written in a different directory.

**Comment by jperkin** [comment]
I've removed the offending text from the `MESSAGE` file. The cvs->git conversion process is currently having difficulties so I can't link to the change, but it will be in the next trunk build.
