### ISSUE TITLE
Tailscale version update

### ISSUE THREAD

**Issue by nheimlich** [TritonDataCenter/pkgsrc#379]
Tailscale 1.44.0 is listed [here](https://smartos.org/packages/set/trunk-x86_64/search/tailscale), but it is quite a bit behind the current version. Is it possible to get this built with newer versions on a regular cadence?

I am willing to participate in helping get these packages added.

**Comment by jperkin** [comment]
As I'm a bit behind things right now I've just done this myself for now. I'll show you how to go about it next time if you like.
