### ISSUE TITLE
percona-cluster 8.0.x sst crashes

### ISSUE THREAD

**Issue by xmerlin** [TritonDataCenter/pkgsrc#380]
After resolving the encoding issue of bug #377, I re-tested Percona Cluster 8.0.x and, although the MySQL client crash is no longer present, the replication and cluster initialization do not work properly. The primary machine set to provide the initial information does not complete the transfer to the joiners correctly, and various MySQL processes are marked as <defunct>. I tested up to version 8.0.36.

**Comment by xmerlin** [comment]
this patch solves the issue
[patch-scripts_wsrep__sst__xtrabackup-v2.diff.gz](https://github.com/TritonDataCenter/pkgsrc/files/15211260/patch-scripts_wsrep__sst__xtrabackup-v2.diff.gz)

**Comment by jperkin** [comment]
Thanks for looking at this. I think that will require that coreutils be a `DEPENDS` for the package, as `nproc` is only available if that package is installed. One drawback of using `nproc` is that it doesn't account for the actual CPU resources available to the zone, and will simply return the number of CPU cores available on the entire system. A way to do that without having to use an external package would be something like `psrinfo | wc -l`.

Doing something like `mdata-get sdc:cpu_cap` and calculating based on that would give you accurate numbers, but is only available to the root user.

I'll have a think...

**Comment by xmerlin** [comment]
I've simply reused a section of a previous patch get_proc is already there so we can you it also for the decompress task
