### ISSUE TITLE
Where to find pkgsrc packages for Darwin ppc?

### ISSUE THREAD

**Issue by barracuda156** [TritonDataCenter/pkgsrc#382]
To be clear, I do not expect anything very new to be pre-built, but it is not required. I am rather looking for some rather dated stuff, which could still be better than available elsewhere. For example, GHC 7.10.3 (so far I was able to fix the build of 7.6.3, but not later versions).

**Comment by jperkin** [comment]
We don't build any PPC packages, but Nia has recently been working on Tiger support, and you can find packages here: https://www.netbsd.org/~nia/tigersrc/

**Comment by barracuda156** [comment]
@jperkin My primary interest are 10.5 and 10.6, but this is interesting, thank you. I will take a look.
Is there a convenient way to contact the developer of that? GH repo or at least e-mail (if you happen to know)?

**Comment by jperkin** [comment]
There's a mildly obfuscated email address at the bottom of that page. The GitHub repo is the main pkgsrc repository at https://github.com/NetBSD/pkgsrc

**Comment by barracuda156** [comment]
> There's a mildly obfuscated email address at the bottom of that page.

Aha, thank you. That is enough.
