### ISSUE TITLE
wg-quick is missing from wireguard-tools

### ISSUE THREAD

**Issue by thenktor** [TritonDataCenter/pkgsrc#384]
Hi,

the wireguard-tools packages is missing the `wg-quick` tool on macOS:
```Makefile
MAKE_FLAGS+=	WITH_WGQUICK=no
```

The MacPorts packages provides a working `wg-quick`, so at least it should work on macOS.

**Comment by jperkin** [comment]
Ok I've committed a fix for this, but it may be a little while before it shows up in the package repository as we're currently waiting on a rebuild of the cvs->git conversion.

**Comment by thenktor** [comment]
Tested and works 👍
