### ISSUE TITLE
Please add ALAC headers to alac package

### ISSUE THREAD

**Issue by thenktor** [TritonDataCenter/pkgsrc#385]
Hi,

please add the `ALAC*.h` headers (https://github.com/macosforge/alac/tree/master/codec) to the alac package. They are needed to compile some software, e.g. squeezelite (https://github.com/ralph-irving/squeezelite).

Thanks!

**Comment by thenktor** [comment]
Also `libalac.a` is missing from the package.

**Comment by jperkin** [comment]
Hi, these are all available in the `libalac` package:

```
$ pkg_info -qL libalac
/opt/local/include/ALACAudioTypes.h
/opt/local/include/ALACBitUtilities.h
/opt/local/include/ALACDecoder.h
/opt/local/include/ALACEncoder.h
/opt/local/include/EndianPortable.h
/opt/local/include/aglib.h
/opt/local/include/dplib.h
/opt/local/include/matrixlib.h
/opt/local/lib/libalac.la
/opt/local/lib/libalac.a
/opt/local/lib/libalac.so
/opt/local/lib/libalac.so.0
/opt/local/lib/libalac.so.0.0.0
```

Cheers.

**Comment by thenktor** [comment]
Sorry, my fault. Thanks for the hint.
