### ISSUE TITLE
package request: Caddy webserver

### ISSUE THREAD

**Issue by thenktor** [TritonDataCenter/pkgsrc#387]
Hi,

would be nice to have a package for Caddy webserver: https://caddyserver.com/

**Comment by teutat3s** [comment]
`caddy` itself [is packaged](https://github.com/NetBSD/pkgsrc/tree/trunk/www/caddy), it just does not have a SMF service yet. Did you try `pkgin in caddy` already?

**Comment by thenktor** [comment]
Oh, indeed it's available in the repo:
```
% uname -mrs
Darwin 23.4.0 arm64

% pkgin search caddy
caddy-2.7.6nb1       General-purpose web server
```

My fault was, that I was looking for it on OmniOS:
```
root in omnios in ~
# uname -mrvs
SunOS 5.11 omnios-r151048-78ef87aa2a4 i86pc

root in omnios in ~
# pkgin search caddy
No results found for caddy
```

Are build logs available for the different systems? I guess caddy fails to build on Solaris and therefore it is missing there?

**Comment by teutat3s** [comment]
You're right, the build is currently [failing](https://us-central.manta.mnx.io/pkgsrc/public/reports/trunk/x86_64/20240514.0214/caddy-2.7.6nb1/build.log), notably:

```
go.step.sm/linkedca
# github.com/caddyserver/caddy/v2
./listen_unix_setopt.go:7:30: undefined: unix.SO_REUSEPORT
```

There's some movement [1](https://code.illumos.org/c/illumos-gate/+/3457) [2](https://www.illumos.org/issues/12455) on `SO_REUSEPORT` for illumos, but we had patches to remove it in the past, that got removed in https://github.com/NetBSD/pkgsrc/commit/d3b56e4b4794bb4d1d7d3f18787a25563511897b. I'll see if I can fix the build.

**Comment by jperkin** [comment]
I've merged in the upstream fix for this from https://github.com/caddyserver/caddy/pull/6021. The next build should include it.

As for the build logs, they are posted to the pkgsrc-bulk list, archive is here: https://mail-index.netbsd.org/pkgsrc-bulk/

The builds that gets published to the OmniOS repository are the "pkgsrc-trunk-x86_64 SmartOS 20210826T002459Z" ones.
