### ISSUE TITLE
[support] Builder status dashboard 

### ISSUE THREAD

**Issue by kaznovac** [TritonDataCenter/pkgsrc#388]
Hi, is there a dashboard to see and inspect package build status?
e.g. https://ports.macports.org/all_builds/

I'm asking because some packages exist in this `pkgsrc` repo (like `pkg`, `ncdu2`, ...) but there is no build for them in the darvin repo https://pkgsrc.smartos.org/packages/Darwin/12.3/arm64/All/

p.s. i find `pkgin` the sanest macos package manager, I will try to contribute a few patches :)

**Comment by jperkin** [comment]
The build reports are posted to the pkgsrc-bulk list, the archive is available here: https://mail-index.netbsd.org/pkgsrc-bulk/

For example here is the most recent macOS/arm64 build: https://mail-index.netbsd.org/pkgsrc-bulk/2024/06/22/msg025424.html

There is also https://releng.netbsd.org/bulktracker/ which attempts to consolidate the reports into a web interface.

Patches would be most welcome! There's plenty of low-hanging fruit to fix, and it's very rewarding work.
