### ISSUE TITLE
Does this work on RISC-V?

### ISSUE THREAD

**Issue by barracuda156** [TritonDataCenter/pkgsrc#389]
I am not sure if NetBSD itself can be installed on RISC-V, but the question is relevant regardless, since I could use `pkgsrc` on Linux in the worst case.

**Comment by jperkin** [comment]
For pkgsrc itself there are no architectural reasons why not, and yes there is NetBSD/riscv support.  General software support will vary though, depending on the host platform.

**Comment by barracuda156** [comment]
@jperkin Thank you, I will just try it then.

**Comment by barracuda156** [comment]
Just for the record, if someone bumps into this topic: YES, `pkgsrc` bootstraps neatly on RISC-V and installing software from source works (I am sure some won’t compile, but the build system itself works fine).
