### ISSUE TITLE
Update go-hugo to a recent version

### ISSUE THREAD

**Issue by thenktor** [TritonDataCenter/pkgsrc#393]
Hi,

please update go-hugo to "current" version: [v0.136.3](https://github.com/gohugoio/hugo/releases/tag/v0.136.3)

Version 0.125 is quite outdated.

Thanks!

**Comment by jperkin** [comment]
I updated it to 0.136.4 just now.  We're always on the lookout for new maintainers who can keep up with software that is frequently updated, so if you're interested please get in touch!
