### ISSUE TITLE
[illumos] net/syncthing fails to compile on SmartOS

### ISSUE THREAD

**Issue by john-tho** [TritonDataCenter/pkgsrc#41]
The [net/syncthing](https://github.com/joyent/pkgsrc/tree/trunk/net/syncthing) package currently builds all of the syncthing family of binaries, but only uses the syncthing binary.
The stdiscosrv binary fails to build for solaris specific problems in a dependency (mmap-go)

Is is possible to build only the syncthing binary on SmartOS?
with:
```
go run build.go install syncthing
```

**Comment by jperkin** [comment]
I fixed this in cdebdfb7d2fe1d58895f8a05d914773339d60773 and will backport to 2017Q4.
