### ISSUE TITLE
AAAA record for pkgsrc.joyent.com?

### ISSUE THREAD

**Issue by jgc234** [TritonDataCenter/pkgsrc#47]
This is probably the wrong place since it's not a code issue, but I'm unsure where to ask.  How do you update  IPv6-only smartos instance with pkgin?  There is no AAAA record for pkgsrc.joyent.com.. I'm currently provisioning legacy IPv4 addresses for every instance.  Any plans for an IPv6 path to the update farm?

Thank you.

**Comment by jperkin** [comment]
It's something I'd love to provide but unfortunately we don't support it at the moment. I'll leave this ticket open anyway so that I can update you as and when we add support.

**Comment by jperkin** [comment]
It's also worth noting that other users in this situation have set up caching proxies or their own pkgsrc rsync mirrors so while not ideal they may be workarounds that better suit you than having to provision IPv4 for all hosts.

**Comment by jgc234** [comment]
@jperkin - Thank you.. A caching proxy with an IPv6 front-end sounds like a plan for the short term - top idea.
