### ISSUE TITLE
Remove-all/reset/pristine command?

### ISSUE THREAD

**Issue by yb66** [TritonDataCenter/pkgsrc#51]
Hi,

I've done an OS upgrade (to High Sierra, yikes!) and since I had a package fail on me (ffmpeg) and reinstallation didn't fix it, I thought it a good time to clear the decks and reinstall all my packages, but I can't find a command to do that e.g. `pkgin reset` or the like.

Is there such a command or would blitzing the /opt/pkg directory and reinstalling pkgsrc be the best way forward?

Regards,
iain

**Comment by jperkin** [comment]
Running `rm -rf /opt/pkg /var/db/pkgin` should give you a clean slate ready for a fresh install.  Depending on what packages you installed there may be some additional leftovers under `/var` but that shouldn't matter too much.

It would be interesting to know what the errors were, in case it's something we can fix.

**Comment by yb66** [comment]
Thanks very much for that, the removal and reinstall means ffmpeg is now working. The problem with ffmpeg was similar to the ones people are having in [this SO question](https://stackoverflow.com/q/26431918/335847) "image not found" error, but they're having the same problem while using Homebrew to install it so at least it's (probably:) not a pkgsrc problem. I'm guessing a linked library changed during the upgrade or something like that but I've no real idea. Let me know if there's something I should check for.

## Note! ##

A note for anyone else reading this advice is to remember to make sure your shell is not set to the one you installed with pkgsrc when you run the `rm` command! (o_O) That took a little sorting out…
