### ISSUE TITLE
Enable DTRACE suppor in Python 3.6.*

### ISSUE THREAD

**Issue by jcea** [TritonDataCenter/pkgsrc#55]
Python 3.6 supports DTRACE when compiled with "--with-dtrace". This flag should be default in SmartOS.

Some details:

https://bugs.python.org/issue21590
https://docs.python.org/3.6/howto/instrumentation.html

**Comment by jperkin** [comment]
This was done a while back in 93e60bfcc39ba16810c7da9dafba983027c47960
