### ISSUE TITLE
py27-pygit2 should depend on git-base

### ISSUE THREAD

**Issue by sjorge** [TritonDataCenter/pkgsrc#57]
It doesn't look like pygit2 works without the git command line tools being available.
It took me a while to figure this for #56 
```[ERROR   ] The git command line utility is required when using the 'pygit2' gitfs_provider.```

**Comment by mamash** [comment]
That doesn't seem likely. pygit2 builds and successfully completes all tests even with no 'git' command available, and I've been able to test a few examples available on their site just fine.

The error message above isn't even part of the pygit2 code. Sounds more like an issue with the pygit2/SaltStack integration?

**Comment by mamash** [comment]
I just updated the package to the latest and brought it into the main pkgsrc tree while at it.

**Comment by sjorge** [comment]
Alright, let’s close this then.
