### ISSUE TITLE
PowerDNS Authorative Server & PowerDNS Recursor need version bump

### ISSUE THREAD

**Issue by jussisallinen** [TritonDataCenter/pkgsrc#58]
PowerDNS Authorative Server (powerdns) could use version bump, current 4.0.4 report's following upon startup:

```
PowerDNS Security Update Mandatory: Upgrade now, see https://doc.powerdns.com/authoritative/security-advisories/powerdns-advisory-2017-04.html
```
Latest version as of now is 4.1.0:
[Changelog](https://doc.powerdns.com/authoritative/changelog/)

PowerDNS Recursor (pdns-recursor) also has newer version which is 4.1.0:
[Changelog](https://doc.powerdns.com/recursor/changelog/)

**Comment by mamash** [comment]
Yes, I have 4.1.x update staging, it's the recursor code that no longer builds properly. Hang on for a bit.

**Comment by jussisallinen** [comment]
Great, thanks a lot already!

**Comment by mamash** [comment]
Upstream in trunk now. This deserves a security fix backport though.

**Comment by mamash** [comment]
Ported back to 2017Q4, pending a branch rebuild.

**Comment by mamash** [comment]
Available in 2017Q4 now.

**Comment by jussisallinen** [comment]
Great thanks for the info!
