### ISSUE TITLE
[request] Dovecot 2.3.0

### ISSUE THREAD

**Issue by jussisallinen** [TritonDataCenter/pkgsrc#59]
Doveot 2.3.0 has been released and 2.2.x will be eventually retired:
https://dovecot.org/list/dovecot-news/2017-December/000366.html

**Comment by jussisallinen** [comment]
Should current Dovecot2 just eventually be bumped to 2.3.x, ie. at latest once 2.2.x hits it's final release some time next year?

**Comment by mamash** [comment]
No reason not to bump to 2.3.0 already. I'm working on the update now.

**Comment by mamash** [comment]
Commited upstream.
