### ISSUE TITLE
dblatex broken on Darwin trunk and SmartOS 17.2.0

### ISSUE THREAD

**Issue by melloc** [TritonDataCenter/pkgsrc#6]
`dblatex-0.3.8` doesn't work with the `tex-multirow-2.2` package. This was [reported on bugs.debian.org](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=840189), and the maintainer has fixed the issue in the [most recent release](https://sourceforge.net/projects/dblatex/files/dblatex/dblatex-0.3.10/) (`dblatex-0.3.10`).

**Comment by jperkin** [comment]
Updated in 8b5cd6a6bbeeb71b22179a5ee0c0325b26077d46, will be in the next Darwin build.

**Comment by jperkin** [comment]
This is now available in the x86_64 repository.
