### ISSUE TITLE
sbcl

### ISSUE THREAD

**Issue by catalinbostan** [TritonDataCenter/pkgsrc#61]
please include sbcl.

http://sbcl.org/platform-table.html

**Comment by mamash** [comment]
pkgsrc does have sbcl, but it may not compile on some platforms. Which platform are you not finding it for?

**Comment by catalinbostan** [comment]
jperkin added right now sbcl-1.4.3 (newer than 1.3.21 from NetBSD/pkgsrc) on  2017Q4
happy :)
