### ISSUE TITLE
Incorrect library version linked in php-7.1.12 in 2017Q4

### ISSUE THREAD

**Issue by FilipFrancis** [TritonDataCenter/pkgsrc#62]
Hi all,

Just upgraded to the latest version of 2017Q4 did a full-upgrade.
and that included php-7.1.12 and found a small issue with it.
As i am running nextcloud and this needs gd so after the upgrade was getting gd not loaded it was configured but not loaded.
Then after looking at the logs i found the following.
ldd /opt/local/lib/php/20160303/gd.so is giving the following
 libimagequant.so.0 =>    <not found>

so i installed the library and was thinking ok it will be fine but no still <not found>
so after the isntallation of libimagequant i looked if the lib is there and that gives me the following
ls -l libimagequant.so*
lrwxrwxrwx   1 root     root          23 Dec 30 18:47 libimagequant.so -> libimagequant.so.2.0.11
lrwxrwxrwx   1 root     root          23 Dec 30 18:47 libimagequant.so.2 -> libimagequant.so.2.0.11
-rwxr-xr-x   1 root     root       72584 Dec 30 18:47 libimagequant.so.2.0.11
So here you can see there is no ibimagequant.so.0
so the only thing that i did is made a symlink from ibimagequant.so.0 to ibimagequant.so
and now the php is working great again as it found the library.
So just to let you know that i had this problem
Regards
Filip

**Comment by mamash** [comment]
This should be fixed in 2017Q4 as of last weekend's rebuild.
