### ISSUE TITLE
[darwin/trunk] git broken after upgrade

### ISSUE THREAD

**Issue by sjorge** [TritonDataCenter/pkgsrc#63]
After the latest set of updates git broke, probably some other commands too.
After updating git showed an error comming from nghttp2.

nghttp2 was linked to an older version of libcurl, the last set of updates did include a newer version of curl. So that is probably why.

This was fixed by doing a ```pkgin install -F nghttp2```. Not sure if this is fixable... this is probably because the version of nghttp2 did not change so it was not upgrade... while there was a rebuild version available? Linking is hard :(

**Comment by mamash** [comment]
I couldn't reproduce just now when I did a full upgrade of my Mac. Sounds like curl wasn't bumped properly when the nghttp2 dependency changed a major lib version, or git-base wasn't when curl updated similar wise.
