### ISSUE TITLE
sysutils/syslog-ng 3.12.2 restart loop

### ISSUE THREAD

**Issue by minusdelta** [TritonDataCenter/pkgsrc#64]
`syslog-ng-3.12.2` is restarting constantly in a smartos (`build: 20171207T064532Z`) minimal-64-lts  17.4.0 zone (`UUID 62aaa296-f143-11e7-bd81-9be1bda071f7`).
Tested both w/ custom and example config, `/var/log/messages`:
```
Jan 10 10:58:44 localhost syslog-ng[90588]: syslog-ng starting up; version='3.13.2'
Jan 10 10:58:55 localhost syslog-ng[90591]: syslog-ng starting up; version='3.13.2'
Jan 10 10:59:06 localhost syslog-ng[90593]: syslog-ng starting up; version='3.13.2'
 .
 .
 .
```
et c.

**Comment by mamash** [comment]
Thanks for the note, possibly related to this ivykis bug...

https://github.com/buytenh/ivykis/issues/12

Not the same issue, but likely a problem with the eventport implementation in ivykis.

**Comment by mamash** [comment]
Turns out the ivykis dependency needs to be built with pthread support (prior to 0.42 this used to be the default).

**Comment by minusdelta** [comment]
Thanks for looking into it and the update!

**Comment by mamash** [comment]
Ported back to 2017Q4, pending a branch rebuild.

**Comment by mamash** [comment]
2017Q4 should have the fixed packages by now.
