### ISSUE TITLE
Default to ghostscript-agpl over ghostscript-gpl

### ISSUE THREAD

**Issue by stevenwilliamson** [TritonDataCenter/pkgsrc#68]
Currently when a package links against or depends on ghostscript it defaults to ghostscript-gpl.

This is an old version with open security issues. It appears as though ghostscript changed licensing from gpl to agpl and the gpl package is an old snapshot pre the change.

Given that the package is effectively now unsupported it would make sense to change to the ghostscript-agpl package to be the default which is kept current with upstream.

**Comment by jperkin** [comment]
I've switched trunk over to ghostscript-agpl and it will be the default in 2018Q1 onwards.
