### ISSUE TITLE
nagios-nrpe manifest.xml (nrpe.xml) does not work anymore with <method_credential/>

### ISSUE THREAD

**Issue by idodeclare** [TritonDataCenter/pkgsrc#72]
Hello. `svc:/pkgsrc/nrpe:default` (nagios-nrpe-3.2.0) would not start up correctly after upgrade to 2017Q4. I found the `<method_credential user="nagios" group="nagios" />` element now interfering with successful startup. After removing that element and refreshing, `svc:/pkgsrc/nrpe:default` starts up correctly, with the daemon still running as `nagios:nagios` as expected.

**Comment by mamash** [comment]
Thanks, obviously nrpe now switches to the non-privileged user on its own. I fixed the SMF manifest now.
