### ISSUE TITLE
rspamd: Currently broken build and a possible fix

### ISSUE THREAD

**Issue by johngrasty** [TritonDataCenter/pkgsrc#76]
Hi,

So rspamd currently fails with an unknown architecture type error. I added this line the Makefile and it built, installed, and packaged fine. I will be testing to see if it actually works soon.

`CFLAGS+=        -I~/usr/include`

I really don't know the preferred way to fix this, but I do know that it wasn't finding endian.h, and now it does. Hopefully this helps.

John

**Comment by mamash** [comment]
I don't see how that could be a fix, since ~/usr/include doesn't exist (unless you populated it yourself), but I'm going to look into rspamd failure, because it just built for me on a manual build.

**Comment by johngrasty** [comment]
Thanks. I was building it using pkgbuild (the latest image), but on a
server running a pretty old platform.

Thanks for looking into it!

**Comment by mamash** [comment]
There were two problems there: endian detection and lack of fcntl support in some Lua code files. Both issues are not manifest on latest SmartOS platforms where system features were improved, but are a problem on the production 2014-something platform that we use for backwards compatibility to build platforms on.

I've fixed both now in trunk pkgsrc and plan to backport to 2017Q4.

**Comment by mamash** [comment]
Just fixed some issues in the rc.d and SMF files and will conclude with an update to 1.6.5.

**Comment by mamash** [comment]
Submitted as PR to upstream in vstakhov/rspamd#2009.

**Comment by mamash** [comment]
Backported into 2017Q4, the rebuilds are syncing now across the http mirrors.
