### ISSUE TITLE
py-mysqlclient: import version 1.3.12

### ISSUE THREAD

**Issue by wiedi** [TritonDataCenter/pkgsrc#77]
https://gist.github.com/wiedi/cc8285f6260387cbd135e9f9f13504a4

This depends on `MYSQL_PKG_PREFIX` from the `joyent/feature/pbulkmulti/trunk` branch.

**Comment by mamash** [comment]
Thanks, I imported this now - with some readability and pkglint polish, but without the MYSQL_PKG_PREFIX treatment though. That will have to be patched in our feature branches later on, as the feature is not supported in pristine pkgsrc.
