### ISSUE TITLE
nullmailer: pull up bugfix into 2017Q4

### ISSUE THREAD

**Issue by wiedi** [TritonDataCenter/pkgsrc#78]
There was an issue in our nullmailer patches which resulted in: `sendmail: Could not exec nullmailer-inject`

Upstream already had the correct fix (but no new release yet) which I commited in https://github.com/NetBSD/pkgsrc/commit/6cdbbda723d9f5937ed4f16af183dd725d97d3c0 - maybe this can be pulled into the 2017Q4 branch.

**Comment by jfqd** [comment]
I can confirm, that nullmailer is completely broken without this patch.
Would be happy if this would be pulled in soon :)

**Comment by jfqd** [comment]
Ups. Why is this ticket being closed? The commit was for py-polib, not nullmailer.

**Comment by jperkin** [comment]
Stupid GitHub bug where it will match any "hash#number" in any changelog that we push to pkgsrc and apply it to this project, they refuse to change it so we just have to keep going back and re-opening tickets that they've incorrectly auto-closed. To make it even worse, I'm not notified of these auto-closes as I'm the committer, so I'm reliant on others to tell me when it happens :(

**Comment by mamash** [comment]
Backported into 2017Q4, the rebuilds are syncing now across the http mirrors.
