### ISSUE TITLE
base-multiarch-lts 16.4.1 update missed tmux

### ISSUE THREAD

**Issue by jclulow** [TritonDataCenter/pkgsrc#80]
In the last couple of days I did a `pkgin up` and a `pkgin fug` in my _base-multiarch-lts 16.4.1_ zone.  After doing this, `tmux` stopped working.  There appeared to have been an update to `libevent` from 2.0.22nb1 to 2.1.8nb1, after which `tmux` could not find the right libraries:

```
$ ldd $(which tmux)
        libxnet.so.1 =>  /lib/libxnet.so.1
        libsocket.so.1 =>        /lib/libsocket.so.1
        libnsl.so.1 =>   /lib/libnsl.so.1
        libevent-2.0.so.5 =>     (file not found)
        libncurses.so.6 =>       /opt/local/lib/libncurses.so.6
        libresolv.so.2 =>        /lib/libresolv.so.2
        libumem.so.1 =>  /lib/libumem.so.1
        libssp.so.0 =>   /opt/local/gcc49/runtime/lib/./libssp.so.0
        libc.so.1 =>     /lib/libc.so.1
        libmp.so.2 =>    /lib/libmp.so.2
        libmd.so.1 =>    /lib/libmd.so.1
        libgcc_s.so.1 =>         /opt/local/gcc49/runtime/lib/./libgcc_s.so.1
        libm.so.2 =>     /lib/libm.so.2
```

@jperkin told me to try a `pkg_add -U tmux`, which resolved the issue.

**Comment by jperkin** [comment]
I have some binaries up for testing which should resolve this, available in the following gist with some background to the problem:

https://gist.github.com/jperkin/5584bef9bebc4c3917fdfc30d9db3bd8

With it being a reasonable change in behaviour there is some chance of data loss, but if anyone has non-critical hosts that they could test them on, especially those with lots of additional packages installed, that'd be great.

**Comment by jperkin** [comment]
Newer pkgin releases since 2018Q2 handle this correctly.
