### ISSUE TITLE
add duo-unix to tools repo

### ISSUE THREAD

**Issue by bahamat** [TritonDataCenter/pkgsrc#82]

**Comment by mamash** [comment]
Sorry, I forgot about this. Added to tools todax.

**Comment by bahamat** [comment]
I found out that this is only going to work if it’s 32-bit, or also includes 32-bit libs because our PI pam stack is 32-bit.

**Comment by mamash** [comment]
Hm, we can't sneak a 32-bit package into a 64-bit package set though, especially if it links against openssl.

**Comment by bahamat** [comment]
If that works, I’m fine with it.

**Comment by jperkin** [comment]
Should we remove this then? tools will always be 64-bit only, so if it's not worth having as it'll be useless then we should stop building it.

**Comment by bahamat** [comment]
Probably.

**Comment by jperkin** [comment]
Ok, done.
