### ISSUE TITLE
dnsdist has a broken xml-manifest file

### ISSUE THREAD

**Issue by jfqd** [TritonDataCenter/pkgsrc#84]
After Installing dnsdist with ```pkgin in dnsdist``` a ```svcadm enable dnsdist``` leaves the service in maintenance state:

```Could not expand method tokens in "/opt/local/bin/dnsdist -d -u dnsdist -g dnsdist -C %{config_file}": property "config_file" not found. ```

Running the following on the xml-manifest file is fixing it:

```
gsed -i -e 's/<property_group name="dnsdist" type="application">/<property_group name="application" type="application">/' /opt/local/lib/svc/manifest/dnsdist.xml
svccfg import /opt/local/lib/svc/manifest/dnsdist.xml
svcadm clear dnsdist
```

The property-group-name should be ```application``` instead of ```dnsdist```.

**Comment by mamash** [comment]
Thanks, the property group name can be anything but it'd have to be mentioned explicitly in references. I changed it to the usual 'application' one which needs not to be treated.
