### ISSUE TITLE
request ffmpeg3 to be built with opus for out of box vp9/opus webm encoding

### ISSUE THREAD

**Issue by SARSninja** [TritonDataCenter/pkgsrc#85]
default pkg options for ffmpeg3 on SmartOS base-32 version 17.3.0 already include libvpx and vorbis. Please enable opus on build so users can encode webm with vp9 and opus out of the box on smartos

**Comment by mamash** [comment]
I enabled the 'opus' option on our 2017Q4 and trunk SmartOS builds and threw in 'x265' too as that only took a small fix in multimedia/x265 to make it build. A 2017Q4 rebuild is in progress now.
