### ISSUE TITLE
clang++ missing iostream header

### ISSUE THREAD

**Issue by mcandre** [TritonDataCenter/pkgsrc#91]
The "clang" package provides a broken clang++ out of the box, as the iostream header file is missing.

When the "gcc49" package is installed, then a g++ binary can compile C++ source that uses iostream. However, clang++ continues to fail to find the header. I'm attempting compilation within a SmartOS global zone environment, in case that matters.

Please fix the "clang" package so that its clang++ can actually compile Hello World C++ programs! Have the "clang" package depend on the "gcc49" package, and setup clang++ so that it can find the headers provided by the "gcc49" package.

**Comment by jperkin** [comment]
clang/llvm 6 is available in newer releases and works correctly.
