### ISSUE TITLE
pkgsrc tools collection should use node LTS releases

### ISSUE THREAD

**Issue by bahamat** [TritonDataCenter/pkgsrc#94]
Right now the only packages available are

```
[root@smartos-iso /var/tmp]# pkgin avail | grep nodejs
nodejs-0.8.28        V8 JavaScript for clients and servers
nodejs-9.10.1        V8 JavaScript for clients and servers
```

Neither of which are suitable for production use.

**Comment by mamash** [comment]
Thanks, that makes sense. I just added allů the LTS releases to the tools subset and let 2017Q4 rebuild.
