### ISSUE TITLE
TLS SNI broken with nginx on 2017Q4

### ISSUE THREAD

**Issue by bahamat** [TritonDataCenter/pkgsrc#95]
This affects both nginx 1.12.2 and 1.13.7. This does not affect Apache.

When visiting a server properly configured with SNI, only one server stanza is used. The certificate and content served for all SSL sites are from the first SSL enabled host.

**Comment by bahamat** [comment]
This was on a SmartOS base-64-lts@17.4.0 image.

**Comment by nbxorg** [comment]
nginx 1.13.3 on SmartOS minimal-64-lts@16.4.1 seems to work ok.

**Comment by mamash** [comment]
Brian, works for me with 1.13.7 on a base-lts-17.4.0 VM. Can you share your config bits?

**Comment by bahamat** [comment]
Actually, looking at my config again I did have an error on the `server_name` that was the problem. Fixing that did resolve it, so this isn't an issue after all.

**Comment by nbxorg** [comment]
Same for me. In the template I was basing my configs off of there was a semi-colon missing from the index statement just before the `server_name` ...

I'm increasingly catching my brain seeing punctuation that isn't really there.
