### ISSUE TITLE
nodejs in tools distro should not depend on python

### ISSUE THREAD

**Issue by bahamat** [TritonDataCenter/pkgsrc#97]
Chatted with @jperkin, tools could set `PYTHON_FOR_BUILD_ONLY=yes`

**Comment by mamash** [comment]
There's also the option of configuring using --without-npm and going with a npm-less package. FreeBSD ports has the node package(s) implemented this way, then provides separate npm packages.

**Comment by jperkin** [comment]
This is done for 2018Q1 and new packages are available (if already installed then `pkg_add -U` them).

**Comment by bahamat** [comment]
So, will this be available if I bootstrapped from 2017Q4-tools?

**Comment by jperkin** [comment]
I didn't force a rebuild of 2017Q4, I prefer not to do things like that in an LTS release and it's better that users always use the latest, but I can do if necessary.
